const data = {
  1: [  { jp: "わたし", id: "saya" },
  { jp: "あなた", id: "kamu" },
  { jp: "あのひと", id: "orang itu (biasa)" },
  { jp: "あのかた", id: "orang itu (sopan)" },
  { jp: "~さん", id: "saudara" },
  { jp: "~ちゃん", id: "panggilan anak laki/perempuan" },
  { jp: "~じん", id: "orang (kewarganegaraan)" },
  { jp: "せんせい", id: "guru, dosen" },
  { jp: "きょうし", id: "guru (kalangan sendiri)" },
  { jp: "がくせい", id: "siswa, murid" },
  { jp: "かいしゃいん", id: "pegawai perusahaan" },
  { jp: "しゃいん", id: "pegawai perusahaan" },
  { jp: "ぎんこういん", id: "pegawai bank" },
  { jp: "いしゃ", id: "dokter" },
  { jp: "けんきゅうしゃ", id: "peneliti" },
  { jp: "だいがく", id: "universitas" },
  { jp: "びょういん", id: "rumah sakit" },
  { jp: "だれ", id: "siapa (biasa)" },
  { jp: "どなた", id: "siapa (sopan)" },
  { jp: "~さい", id: "umur" },
  { jp: "なんさい", id: "umur berapa (biasa)" },
  { jp: "おいくつ", id: "umur berapa (sopan)" },
  { jp: "はい", id: "iya" },
  { jp: "いいえ", id: "tidak" },
  { jp: "はじめまして", id: "perkenalkan" },
  { jp: "~からきました", id: "datang dari" },
  { jp: "どうぞよろしくおねがいします", id: "terimalah perkenalan saya" },
  { jp: "しつれいですが", id: "permisi" },
  { jp: "おなまえは", id: "nama anda siapa" },
  { jp: "アメリカ", id: "amerika" },
  { jp: "イギリス", id: "inggris" },
  { jp: "インド", id: "india" },
  { jp: "インドネシア", id: "indonesia" },
  { jp: "かんこく", id: "korea" },
  { jp: "ちゅうごく", id: "china" },
  { jp: "ドイツ", id: "jerman" },
  { jp: "にほん", id: "jepang" },
  { jp: "フランス", id: "perancis" }],
  2: [{ jp: "これ", id: "ini" },
  { jp: "それ", id: "itu (dekat)" },
  { jp: "あれ", id: "itu (jauh)" },
  { jp: "この~", id: "~ini" },
  { jp: "その~", id: "~itu (dekat)" },
  { jp: "あの~", id: "~itu (jauh)" },
  { jp: "ほん", id: "buku" },
  { jp: "じしょ", id: "kamus" },
  { jp: "ざっし", id: "majalah" },
  { jp: "しんぶん", id: "koran" },
  { jp: "ノート", id: "buku catatan" },
  { jp: "てちょう", id: "buku agenda" },
  { jp: "めいし", id: "kartu nama" },
  { jp: "カード", id: "kartu" },
  { jp: "えんぴつ", id: "pensil" },
  { jp: "ボールペン", id: "bolpoin" },
  { jp: "シャープペンシル", id: "pensil mekanik" },
  { jp: "かぎ", id: "kunci" },
  { jp: "とけい", id: "jam, arloji" },
  { jp: "かさ", id: "payung" },
  { jp: "かばん", id: "tas" },
  { jp: "テレビ", id: "televisi" },
  { jp: "ラジオ", id: "radio" },
  { jp: "カメラ", id: "kamera" },
  { jp: "コンピューター", id: "komputer" },
  { jp: "くるま", id: "mobil" },
  { jp: "つくえ", id: "meja" },
  { jp: "いす", id: "kursi" },
  { jp: "チョコレート", id: "cokelat" },
  { jp: "コーヒー", id: "kopi" },
  { jp: "おみやげ", id: "oleh-oleh" },
  { jp: "えいご", id: "bahasa inggris" },
  { jp: "にほんご", id: "bahasa jepang" },
  { jp: "~ご", id: "bahasa ~" },
  { jp: "なん", id: "apa" },
  { jp: "そう", id: "begitu" },
  { jp: "あのう", id: "eee… (ragu)" },
  { jp: "えっ", id: "eh (kaget)" },
  { jp: "どうぞ", id: "silakan" },
  { jp: "どうもありがとうございます", id: "terima kasih banyak" },
  { jp: "そうですか", id: "oh begitu, benarkah?" },
  { jp: "ちがいます", id: "bukan, tidak, salah" },
  { jp: "あ", id: "oh, eh (sadar)" },
  { jp: "これからおせわになります", id: "mulai sekarang saya akan meminta bantuannya" },
  { jp: "こちらこそよろしくおねがいします", id: "ya sama-sama" }],
  3: [  { jp: "ここ", id: "di sini" },
  { jp: "そこ", id: "di situ" },
  { jp: "あそこ", id: "di sana" },
  { jp: "どこ", id: "di mana?" },
  { jp: "こちら", id: "di sini" },
  { jp: "そちら", id: "di situ" },
  { jp: "あちら", id: "di sana" },
  { jp: "どちら", id: "di mana?" },
  { jp: "きょうしつ", id: "ruang kelas" },
  { jp: "しょくどう", id: "ruang makan, kantin" },
  { jp: "じむしょ", id: "kantor" },
  { jp: "かいぎしつ", id: "ruang rapat" },
  { jp: "うけつけ", id: "meja informasi" },
  { jp: "ロビー", id: "ruang tunggu, lobi" },
  { jp: "へや", id: "kamar" },
  { jp: "おてあらい", id: "kamar kecil, WC" },
  { jp: "トイレ", id: "toilet" },
  { jp: "かいだん", id: "tangga" },
  { jp: "エレベーター", id: "lift" },
  { jp: "エスカレーター", id: "eskalator, tangga berjalan" },
  { jp: "じどうはんばいき", id: "mesin jual otomatis" },
  { jp: "でんわ", id: "telepon" },
  { jp: "おくに", id: "negara" },
  { jp: "かいしゃ", id: "perusahaan" },
  { jp: "うち", id: "rumah" },
  { jp: "くつ", id: "sepatu" },
  { jp: "ネクタイ", id: "dasi" },
  { jp: "ワイン", id: "anggur putih" },
  { jp: "うりば", id: "tempat penjualan" },
  { jp: "ちか", id: "bawah tanah, basement" },
  { jp: "~かい", id: "lantai / tingkat ~" },
  { jp: "なんがい", id: "lantai berapa?" },
  { jp: "~えん", id: "yen" },
  { jp: "いくら", id: "berapa?" },
  { jp: "ひゃく", id: "seratus" },
  { jp: "せん", id: "seribu" },
  { jp: "まん", id: "puluh ribu" },
  { jp: "すみません", id: "maaf" },
  { jp: "どうも", id: "terima kasih" },
  { jp: "いらっしゃいませ", id: "selamat datang" },
  { jp: "みせてください", id: "tolong perlihatkan" },
  { jp: "じゃ", id: "kalau begitu" },
  { jp: "~をください", id: "tolong ~" },
  { jp: "イタリア", id: "italia" },
  { jp: "スイス", id: "swis" },
  { jp: "フランス", id: "perancis" },
  { jp: "ジャカルタ", id: "jakarta" },
  { jp: "バンコク", id: "bangkok" },
  { jp: "ベルリン", id: "berlin" },
  { jp: "おくじょう", id: "lantai atas" },
  { jp: "レストラン", id: "restoran" },
  { jp: "ゆうえんち", id: "tempat hiburan" },
  { jp: "もよおしものかいじょう", id: "tempat pertunjukan" },
  { jp: "めがね", id: "kacamata" }],
  4: [  { jp: "おきます", id: "bangun tidur" },
  { jp: "ねます", id: "tidur" },
  { jp: "はたらきます", id: "bekerja" },
  { jp: "やすみます", id: "beristirahat, libur" },
  { jp: "べんきょうします", id: "belajar" },
  { jp: "おわります", id: "selesai" },
  { jp: "デパート", id: "departemen store" },
  { jp: "ぎんこう", id: "bank" },
  { jp: "ゆうびんきょく", id: "kantor pos" },
  { jp: "としょかん", id: "perpustakaan" },
  { jp: "びじゅつかん", id: "gedung kesenian" },
  { jp: "いま", id: "sekarang" },
  { jp: "~じ", id: "jam, pukul" },
  { jp: "~ふん", id: "menit" },
  { jp: "はん", id: "setengah" },
  { jp: "なんじ", id: "jam berapa?" },
  { jp: "なんぷん", id: "berapa menit?" },
  { jp: "ごぜん", id: "AM (sebelum jam 12 siang)" },
  { jp: "ごご", id: "PM (setelah jam 12 siang)" },
  { jp: "あさ", id: "pagi" },
  { jp: "ひる", id: "siang" },
  { jp: "ばん", id: "malam" },
  { jp: "よる", id: "malam" },
  { jp: "おととい", id: "kemarin lusa" },
  { jp: "きのう", id: "kemarin" },
  { jp: "きょう", id: "hari ini" },
  { jp: "あした", id: "besok" },
  { jp: "あさって", id: "besok lusa" },
  { jp: "けさ", id: "tadi pagi" },
  { jp: "こんばん", id: "malam ini" },
  { jp: "やすみ", id: "istirahat, cuti, libur" },
  { jp: "ひるやすみ", id: "istirahat siang" },
  { jp: "しけん", id: "ujian" },
  { jp: "かいぎ", id: "rapat" },
  { jp: "えいが", id: "film" },
  { jp: "まいあさ", id: "setiap pagi" },
  { jp: "まいばん", id: "setiap malam" },
  { jp: "まいにち", id: "setiap hari" },
  { jp: "げつようび", id: "hari senin" },
  { jp: "かようび", id: "hari selasa" },
  { jp: "すいようび", id: "hari rabu" },
  { jp: "もくようび", id: "hari kamis" },
  { jp: "きんようび", id: "hari jumat" },
  { jp: "どようび", id: "hari sabtu" },
  { jp: "にちようび", id: "hari minggu" },
  { jp: "なんようび", id: "hari apa?" },
  { jp: "~から", id: "dari" },
  { jp: "~まで", id: "sampai" },
  { jp: "~と~", id: "dan" },
  { jp: "たいへんですね", id: "berat ya" },
  { jp: "ばんごう", id: "nomor" },
  { jp: "なんばん", id: "nomor berapa?" },
  { jp: "ニューヨーク", id: "new york" },
  { jp: "ペキン", id: "beijing" },
  { jp: "ロサンゼルス", id: "los angeles" },
  { jp: "ロンドン", id: "london" },
  { jp: "けいさつしょ", id: "kantor polisi" },
  { jp: "しょうぼうしょ", id: "pemadam kebakaran" },
  { jp: "じほう", id: "pemberitahuan waktu" },
  { jp: "てんきよほう", id: "ramalan cuaca" },
  { jp: "でんわばんごうあんない", id: "petunjuk nomor telepon" }],
  5: [{ jp: "いきます", id: "pergi" },
  { jp: "きます", id: "datang" },
  { jp: "かえります", id: "pulang" },
  { jp: "がっこう", id: "sekolah" },
  { jp: "スーパー", id: "supermarket" },
  { jp: "えき", id: "stasiun" },
  { jp: "ひこうき", id: "pesawat terbang" },
  { jp: "ふね", id: "kapal laut" },
  { jp: "でんしゃ", id: "kereta listrik" },
  { jp: "ちかてつ", id: "kereta bawah tanah" },
  { jp: "しんかんせん", id: "shinkansen" },
  { jp: "バス", id: "bus" },
  { jp: "タクシー", id: "taksi" },
  { jp: "じてんしゃ", id: "sepeda" },
  { jp: "あるいて", id: "jalan kaki" },
  { jp: "ひと", id: "orang" },
  { jp: "ともだち", id: "teman" },
  { jp: "かれ", id: "dia (laki-laki)" },
  { jp: "かのじょ", id: "dia (perempuan)" },
  { jp: "かぞく", id: "keluarga" },
  { jp: "ひとりで", id: "sendirian" },
  { jp: "せんしゅう", id: "minggu lalu" },
  { jp: "こんしゅう", id: "minggu ini" },
  { jp: "らいしゅう", id: "minggu depan" },
  { jp: "せんげつ", id: "bulan lalu" },
  { jp: "こんげつ", id: "bulan ini" },
  { jp: "らいげつ", id: "bulan depan" },
  { jp: "きょねん", id: "tahun lalu" },
  { jp: "ことし", id: "tahun ini" },
  { jp: "らいねん", id: "tahun depan" },
  { jp: "~ねん", id: "tahun" },
  { jp: "なんねん", id: "tahun berapa?" },
  { jp: "~がつ", id: "bulan" },
  { jp: "なんがつ", id: "bulan apa?" },
  { jp: "ついたち", id: "tanggal 1" },
  { jp: "ふつか", id: "tanggal 2 / 2 hari" },
  { jp: "みっか", id: "tanggal 3 / 3 hari" },
  { jp: "よっか", id: "tanggal 4 / 4 hari" },
  { jp: "いつか", id: "tanggal 5 / 5 hari" },
  { jp: "むいか", id: "tanggal 6 / 6 hari" },
  { jp: "なのか", id: "tanggal 7 / 7 hari" },
  { jp: "ようか", id: "tanggal 8 / 8 hari" },
  { jp: "ここのか", id: "tanggal 9 / 9 hari" },
  { jp: "とおか", id: "tanggal 10 / 10 hari" },
  { jp: "じゅうよっか", id: "tanggal 14 / 14 hari" },
  { jp: "はつか", id: "tanggal 20 / 20 hari" },
  { jp: "にじゅうよっか", id: "tanggal 24 / 24 hari" },
  { jp: "~にち", id: "tanggal / hari" },
  { jp: "なんにち", id: "tanggal berapa / berapa hari" },
  { jp: "いつ", id: "kapan" },
  { jp: "たんじょうび", id: "hari ulang tahun" },
  { jp: "そうですね", id: "ya begitulah" },
  { jp: "どういたしまして", id: "sama-sama" },
  { jp: "~ばんせん", id: "peron / jalur nomor" },
  { jp: "つぎの", id: "yang berikutnya" },
  { jp: "ふつう", id: "biasa" },
  { jp: "きゅうこう", id: "ekspres" },
  { jp: "とっきゅう", id: "super ekspres" },
  { jp: "しゅくさいじつ", id: "hari libur nasional" },
  { jp: "がんじつ", id: "tahun baru" },
  { jp: "せいじんのひ", id: "hari perayaan menjadi dewasa" },
  { jp: "けんこくきねんのひ", id: "hari pembangunan nasional" },
  { jp: "しゅんぶんのひ", id: "hari ekuinoks musim semi" },
  { jp: "しょうわのひ", id: "hari showa" },
  { jp: "けんぽうきねんび", id: "hari peringatan konstitusi" },
  { jp: "みどりのひ", id: "hari penghijauan" },
  { jp: "こどものひ", id: "hari anak" },
  { jp: "うみのひ", id: "hari bahari" },
  { jp: "やまのひ", id: "hari gunung" },
  { jp: "けいろうのひ", id: "hari hormat kepada orang tua" },
  { jp: "しゅうぶんのひ", id: "hari ekuinoks musim gugur" },
  { jp: "たいいくのひ", id: "hari kesehatan olahraga" },
  { jp: "ぶんかのひ", id: "hari kebudayaan" },
  { jp: "きんろうかんしゃのひ", id: "hari bersyukur untuk pekerjaan" },
  { jp: "てんのうたんじょうび", id: "hari ulang tahun kaisar" }],

  6: [ { jp: "たべます", id: "makan" },
  { jp: "のみます", id: "minum" },
  { jp: "すいます", id: "menghisap / merokok" },
  { jp: "みます", id: "melihat / menonton" },
  { jp: "ききます", id: "mendengar" },
  { jp: "よみます", id: "membaca" },
  { jp: "かきます", id: "menulis / menggambar" },
  { jp: "かいます", id: "membeli" },
  { jp: "とります", id: "mengambil (foto) / memotret" },
  { jp: "します", id: "melakukan / mengerjakan" },
  { jp: "あいます", id: "bertemu" },

  { jp: "ごはん", id: "nasi" },
  { jp: "あさごはん", id: "sarapan" },
  { jp: "ひるごはん", id: "makan siang" },
  { jp: "ばんごはん", id: "makan malam" },
  { jp: "パン", id: "roti" },
  { jp: "たまご", id: "telur" },
  { jp: "にく", id: "daging" },
  { jp: "さかな", id: "ikan" },
  { jp: "やさい", id: "sayuran" },
  { jp: "くだもの", id: "buah-buahan" },
  { jp: "みず", id: "air" },
  { jp: "おちゃ", id: "teh jepang / teh hijau" },
  { jp: "こうちゃ", id: "teh" },
  { jp: "ぎゅうにゅう", id: "susu" },
  { jp: "ジュース", id: "jus" },
  { jp: "ビール", id: "bir" },
  { jp: "おさけ", id: "minuman keras" },
  { jp: "たばこ", id: "rokok" },

  { jp: "てがみ", id: "surat" },
  { jp: "レポート", id: "laporan" },
  { jp: "しゃしん", id: "foto" },
  { jp: "ビデオ", id: "kaset video" },
  { jp: "みせ", id: "toko" },
  { jp: "にわ", id: "halaman" },
  { jp: "しゅくだい", id: "pekerjaan rumah / PR" },

  { jp: "テニス", id: "tenis" },
  { jp: "サッカー", id: "sepak bola" },
  { jp: "はなみ", id: "hanami (menikmati bunga sakura)" },

  { jp: "なに", id: "apa" },
  { jp: "いっしょに", id: "bersama-sama" },
  { jp: "ちょっと", id: "sebentar / sedikit" },
  { jp: "いつも", id: "selalu" },
  { jp: "ときどき", id: "kadang-kadang" },
  { jp: "それから", id: "setelah itu / kemudian" },
  { jp: "ええ", id: "ya" },
  { jp: "いいですね", id: "bagus ya" },
  { jp: "わかりました", id: "mengerti / baik" },
  { jp: "じゃ、また", id: "ok, sampai jumpa" },

  { jp: "メキシコ", id: "meksiko" },

  { jp: "きゅうり", id: "timun" },
  { jp: "トマト", id: "tomat" },
  { jp: "なす", id: "terong" },
  { jp: "まめ", id: "kacang-kacangan" },
  { jp: "キャベツ", id: "kol" },
  { jp: "ねぎ", id: "daun bawang" },
  { jp: "はくさい", id: "sawi" },
  { jp: "ほうれんそう", id: "bayam" },
  { jp: "レタス", id: "selada" },
  { jp: "じゃがいも", id: "kentang" },
  { jp: "だいこん", id: "lobak" },
  { jp: "たまねぎ", id: "bawang" },
  { jp: "にんじん", id: "wortel" },

  { jp: "いちご", id: "stroberi" },
  { jp: "もも", id: "buah persik" },
  { jp: "すいか", id: "semangka" },
  { jp: "ぶどう", id: "anggur" },
  { jp: "なし", id: "pir" },
  { jp: "かき", id: "kesemek" },
  { jp: "みかん", id: "jeruk" },
  { jp: "りんご", id: "apel" },
  { jp: "バナナ", id: "pisang" },

  { jp: "ぎゅうにく", id: "daging sapi" },
  { jp: "とりにく", id: "daging ayam" },
  { jp: "ぶたにく", id: "daging babi" },
  { jp: "ソーセージ", id: "sosis" },
  { jp: "ハム", id: "ham" },

  { jp: "あじ", id: "ikan mackerel" },
  { jp: "いわし", id: "ikan sarden" },
  { jp: "さば", id: "ikan kembung" },
  { jp: "さんま", id: "ikan sauri pasifik" },
  { jp: "さけ", id: "ikan salmon" },
  { jp: "まぐろ", id: "ikan tuna" },
  { jp: "たい", id: "ikan kakap" },
  { jp: "たら", id: "ikan gabus" },
  { jp: "えび", id: "udang" },
  { jp: "かに", id: "kepiting" },
  { jp: "いか", id: "cumi-cumi" },
  { jp: "たこ", id: "gurita" },
  { jp: "こめ", id: "beras" }],
  7:[  { jp: "きります", id: "memotong / menggunting" },
  { jp: "おくります", id: "mengirim" },
  { jp: "あげます", id: "memberikan" },
  { jp: "もらいます", id: "menerima / mendapatkan" },
  { jp: "かします", id: "meminjamkan / menyewakan" },
  { jp: "かります", id: "meminjam / menyewa" },
  { jp: "おしえます", id: "mengajar / memberi tahu" },
  { jp: "ならいます", id: "belajar (kepada)" },
  { jp: "かけます", id: "menelpon" },

  { jp: "て", id: "tangan" },
  { jp: "はし", id: "sumpit" },
  { jp: "スプーン", id: "sendok" },
  { jp: "ナイフ", id: "pisau" },
  { jp: "フォーク", id: "garpu" },
  { jp: "はさみ", id: "gunting" },
  { jp: "パソコン", id: "laptop" },
  { jp: "ケータイ", id: "HP" },
  { jp: "メール", id: "email" },
  { jp: "ねんがじょう", id: "kartu tahun baru" },
  { jp: "パンチ", id: "pelubang kertas" },
  { jp: "ホッチキス", id: "stapler" },
  { jp: "セロテープ", id: "selotip" },
  { jp: "けしゴム", id: "penghapus karet" },
  { jp: "かみ", id: "kertas" },
  { jp: "はな", id: "bunga" },
  { jp: "シャツ", id: "kemeja" },
  { jp: "プレゼント", id: "hadiah / kado" },
  { jp: "にもつ", id: "barang / bawaan" },
  { jp: "おかね", id: "uang" },
  { jp: "きっぷ", id: "karcis / tiket" },
  { jp: "クリスマス", id: "natal" },

  { jp: "ちち", id: "ayah" },
  { jp: "はは", id: "ibu" },
  { jp: "おとうさん", id: "ayah (orang lain)" },
  { jp: "おかあさん", id: "ibu (orang lain)" },

  { jp: "もう", id: "sudah" },
  { jp: "まだ", id: "belum" },
  { jp: "これから", id: "mulai dari sekarang" },
  { jp: "すてきですね", id: "bagus ya / indah ya" },
  { jp: "いらっしゃい", id: "selamat datang" },
  { jp: "どうぞおあがりください", id: "silakan masuk" },
  { jp: "しつれいします", id: "permisi" },
  { jp: "~いかがですか", id: "bagaimana? (menawarkan)" },
  { jp: "いただきます", id: "selamat makan" },
  { jp: "ごちそうさまでした", id: "terima kasih atas hidangannya" },

  { jp: "スペイン", id: "spanyol" },

  { jp: "かぞく", id: "keluarga" },
  { jp: "そぼ", id: "nenek" },
  { jp: "そふ", id: "kakek" },
  { jp: "そふぼ", id: "kakek nenek" },
  { jp: "りょうしん", id: "orang tua" },
  { jp: "いもうと", id: "adik perempuan" },
  { jp: "おとうと", id: "adik laki-laki" },
  { jp: "あね", id: "kakak perempuan" },
  { jp: "あに", id: "kakak laki-laki" },
  { jp: "きょうだい", id: "saudara kandung" },
  { jp: "つま", id: "istri" },
  { jp: "おっと", id: "suami" },
  { jp: "ふうふ", id: "pasangan suami istri" },
  { jp: "むすめ", id: "anak perempuan" },
  { jp: "むすこ", id: "anak laki-laki" },
  { jp: "こども", id: "anak" },

  { jp: "おばあさん", id: "nenek (orang lain)" },
  { jp: "おじいさん", id: "kakek (orang lain)" },
  { jp: "ごりょうしん", id: "orang tua (orang lain)" },
  { jp: "いもうとさん", id: "adik perempuan (orang lain)" },
  { jp: "おとうとさん", id: "adik laki-laki (orang lain)" },
  { jp: "おねえさん", id: "kakak perempuan (orang lain)" },
  { jp: "おにいさん", id: "kakak laki-laki (orang lain)" },
  { jp: "ごきょうだい", id: "saudara kandung (orang lain)" },
  { jp: "おくさん", id: "istri (orang lain)" },
  { jp: "ごふうふ", id: "pasangan suami istri (orang lain)" },
  { jp: "むすめさん", id: "anak perempuan (orang lain)" },
  { jp: "むすこさん", id: "anak laki-laki (orang lain)" },
  { jp: "おこさん", id: "anak (orang lain)" }],


  8: [{ jp: "ハンサム(な)", id: "tampan / ganteng" },
  { jp: "きれい(な)", id: "cantik / bersih" },
  { jp: "しずか(な)", id: "sunyi / tenang" },
  { jp: "にぎやか(な)", id: "ramai" },
  { jp: "ゆうめい(な)", id: "terkenal" },
  { jp: "しんせつ(な)", id: "baik hati" },
  { jp: "げんき(な)", id: "sehat" },
  { jp: "ひま(な)", id: "senggang" },
  { jp: "べんり(な)", id: "praktis" },
  { jp: "すてき(な)", id: "bagus" },

  { jp: "おおきい", id: "besar" },
  { jp: "ちいさい", id: "kecil" },
  { jp: "あたらしい", id: "baru" },
  { jp: "ふるい", id: "lama / tua" },
  { jp: "いい(よい)", id: "baik / bagus" },
  { jp: "わるい", id: "jelek" },
  { jp: "あつい", id: "panas" },
  { jp: "さむい", id: "dingin (suhu)" },
  { jp: "つめたい", id: "dingin (benda)" },
  { jp: "むずかしい", id: "sulit" },
  { jp: "やさしい", id: "mudah" },
  { jp: "たかい", id: "mahal / tinggi" },
  { jp: "やすい", id: "murah" },
  { jp: "ひくい", id: "rendah" },
  { jp: "おもしろい", id: "menarik" },
  { jp: "おいしい", id: "enak" },
  { jp: "いそがしい", id: "sibuk" },
  { jp: "たのしい", id: "senang" },

  { jp: "しろい", id: "putih" },
  { jp: "くろい", id: "hitam" },
  { jp: "あかい", id: "merah" },
  { jp: "あおい", id: "biru" },

  { jp: "さくら", id: "sakura" },
  { jp: "やま", id: "gunung" },
  { jp: "まち", id: "kota" },
  { jp: "たべもの", id: "makanan" },
  { jp: "ところ", id: "tempat" },
  { jp: "りょう", id: "asrama" },
  { jp: "レストラン", id: "restoran" },
  { jp: "せいかつ", id: "kehidupan" },
  { jp: "しごと", id: "pekerjaan" },

  { jp: "どう", id: "bagaimana?" },
  { jp: "どんな~", id: "yang bagaimana?" },
  { jp: "とても", id: "sangat" },
  { jp: "あまり", id: "tidak begitu / kurang begitu" },
  { jp: "そして", id: "kemudian" },
  { jp: "~が~", id: "tetapi" },
  { jp: "おげんきですか", id: "apa kabar?" },
  { jp: "そうですね", id: "bagaimana ya?" },
  { jp: "~もういっぱいいかがですか", id: "mau nambah secangkir lagi?" },
  { jp: "(いいえ)けっこうです", id: "cukup" },
  { jp: "そろそろしつれいします", id: "maaf saya mau pamit dulu" },
  { jp: "いいえ", id: "sama-sama" },
  { jp: "またいらっしゃってください", id: "silakan datang lagi" },

  { jp: "シャンハイ", id: "shanghai" },

  { jp: "みどり", id: "hijau" },
  { jp: "むらさき", id: "ungu" },
  { jp: "きいろい", id: "kuning" },
  { jp: "ちゃいろい", id: "cokelat" },
  { jp: "ピンク", id: "merah muda" },
  { jp: "オレンジ", id: "oranye" },
  { jp: "グレー", id: "abu-abu" },
  { jp: "ベージュ", id: "krem" },

  { jp: "はる", id: "musim semi" },
  { jp: "なつ", id: "musim panas" },
  { jp: "あき", id: "musim gugur" },
  { jp: "ふゆ", id: "musim dingin" }],
  9: [  { jp: "わかります", id: "mengerti" },
  { jp: "あります", id: "ada / mempunyai" },
  { jp: "すき(な)", id: "suka / gemar" },
  { jp: "きらい(な)", id: "benci" },
  { jp: "じょうず(な)", id: "pandai / pintar" },
  { jp: "へた(な)", id: "tidak pandai / kurang pintar" },

  { jp: "のみもの", id: "minuman" },
  { jp: "りょうり", id: "masakan" },
  { jp: "スポーツ", id: "olahraga" },
  { jp: "やきゅう", id: "baseball" },
  { jp: "ダンス", id: "dansa" },
  { jp: "りょこう", id: "tamasya / wisata" },
  { jp: "おんがく", id: "musik" },
  { jp: "うた", id: "lagu" },
  { jp: "クラシック", id: "klasik" },
  { jp: "ジャズ", id: "jazz" },
  { jp: "コンサート", id: "konser" },
  { jp: "カラオケ", id: "karaoke" },
  { jp: "かぶき", id: "kabuki (drama tradisional Jepang)" },
  { jp: "え", id: "gambar" },
  { jp: "じ", id: "huruf" },
  { jp: "かんじ", id: "kanji" },
  { jp: "ひらがな", id: "hiragana" },
  { jp: "かたかな", id: "katakana" },
  { jp: "ローマじ", id: "huruf latin" },

  { jp: "こまかいおかね", id: "uang kecil / receh" },
  { jp: "チケット", id: "tiket" },
  { jp: "じかん", id: "waktu" },
  { jp: "ようじ", id: "urusan" },
  { jp: "やくそく", id: "janji" },
  { jp: "アルバイト", id: "kerja paruh waktu" },

  { jp: "ごしゅじん", id: "suami (orang lain)" },
  { jp: "おっと / しゅじん", id: "suami" },
  { jp: "おくさん", id: "istri (orang lain)" },
  { jp: "つま / かない", id: "istri" },
  { jp: "こども", id: "anak" },

  { jp: "よく", id: "dengan baik" },
  { jp: "だいたい", id: "kira-kira" },
  { jp: "たくさん", id: "banyak" },
  { jp: "すこし", id: "sedikit" },
  { jp: "ぜんぜん", id: "sama sekali" },
  { jp: "はやく", id: "cepat" },

  { jp: "~から", id: "karena" },
  { jp: "どうして", id: "kenapa" },
  { jp: "かしてください", id: "tolong pinjamkan" },
  { jp: "いいですよ", id: "boleh" },
  { jp: "ざんねんです", id: "sayang sekali" },
  { jp: "いっしょにいかがですか", id: "bagaimana kalau bersama-sama" },
  { jp: "~ちょっと…", id: "maaf, saya tidak bisa" },
  { jp: "だめですか", id: "tidak bisa ya / tidak boleh ya" },
  { jp: "またこんどおねがいします", id: "lain kali saja" },

  { jp: "ポップス", id: "pop" },
  { jp: "ロック", id: "rock" },
  { jp: "ラテン", id: "musik latin" },
  { jp: "みんよう", id: "musik rakyat" },
  { jp: "えんか", id: "enka" },
  { jp: "ミュージカル", id: "drama musikal" },
  { jp: "オペラ", id: "opera" },

  { jp: "ホラー", id: "film horor" },
  { jp: "アニメ", id: "film animasi" },
  { jp: "ドキュメンタリー", id: "film dokumenter" },
  { jp: "れんあい", id: "film percintaan" },
  { jp: "ミステリー", id: "film misteri" },
  { jp: "ぶんげい", id: "film kesusastraan" },
  { jp: "せんそう", id: "film peperangan" },
  { jp: "アクション", id: "film action" },
  { jp: "きげき", id: "film komedi" },

  { jp: "ソフトボール", id: "softball" },
  { jp: "サッカー", id: "sepak bola" },
  { jp: "ラグビー", id: "rugby" },
  { jp: "バレーボール", id: "voli" },
  { jp: "テニス", id: "tenis" },
  { jp: "ボウリング", id: "bowling" },
  { jp: "スキー", id: "ski" },
  { jp: "スケート", id: "skate" },
  { jp: "たっきゅう / ピンポン", id: "pingpong" },
  { jp: "すもう", id: "sumo" },
  { jp: "じゅうどう", id: "judo" },
  { jp: "けんどう", id: "kendo" },
  { jp: "すいえい", id: "renang" }],
  10: [{ jp: "あります", id: "ada (benda mati)" },
  { jp: "います", id: "ada (benda hidup)" },
  { jp: "いろいろ(な)", id: "berbagai / macam-macam" },
  { jp: "おとこのひと", id: "orang laki-laki" },
  { jp: "おんなのひと", id: "orang perempuan" },
  { jp: "おとこのこ", id: "anak laki-laki" },
  { jp: "おんなのこ", id: "anak perempuan" },
  { jp: "いぬ", id: "anjing" },
  { jp: "ねこ", id: "kucing" },
  { jp: "パンダ", id: "panda" },
  { jp: "ぞう", id: "gajah" },
  { jp: "き", id: "pohon" },
  { jp: "もの", id: "barang" },
  { jp: "でんち", id: "baterai" },
  { jp: "はこ", id: "kotak" },
  { jp: "スイッチ", id: "saklar" },
  { jp: "れいぞうこ", id: "kulkas" },
  { jp: "テーブル", id: "meja makan" },
  { jp: "ベッド", id: "tempat tidur" },
  { jp: "たな", id: "lemari / rak" },
  { jp: "ドア", id: "pintu" },
  { jp: "まど", id: "jendela" },
  { jp: "ポスト", id: "kotak surat" },
  { jp: "ビル", id: "gedung" },
  { jp: "ATM", id: "ATM" },
  { jp: "コンビニ", id: "toko 24 jam" },
  { jp: "こうえん", id: "taman" },
  { jp: "きっさてん", id: "kafe / coffee shop" },
  { jp: "~や", id: "toko ~" },
  { jp: "のりば", id: "tempat naik" },
  { jp: "けん", id: "prefektur" },
  { jp: "うえ", id: "atas" },
  { jp: "した", id: "bawah" },
  { jp: "まえ", id: "depan" },
  { jp: "うしろ", id: "belakang" },
  { jp: "みぎ", id: "kanan" },
  { jp: "ひだり", id: "kiri" },
  { jp: "なか", id: "dalam" },
  { jp: "そと", id: "luar" },
  { jp: "となり", id: "sebelah / samping" },
  { jp: "ちかく", id: "dekat" },
  { jp: "あいだ", id: "antara" },
  { jp: "どうもすみません", id: "maaf / terima kasih banyak" },
  { jp: "ナンプラー", id: "kecap ikan" },
  { jp: "コーナー", id: "bagian penjualan" },
  { jp: "いちばんした", id: "paling bawah" },
  { jp: "げんかん", id: "pintu masuk" },
  { jp: "ふろば", id: "kamar mandi" },
  { jp: "せんめんじょ", id: "tempat cuci tangan" },
  { jp: "だいどころ", id: "dapur" },
  { jp: "しょくどう", id: "kantin / ruang makan" },
  { jp: "いま", id: "ruang tamu" },
  { jp: "しんしつ", id: "kamar tidur" },
  { jp: "ろうか", id: "koridor" },
  { jp: "ベランダ", id: "teras" }],

  11: [
  { jp: "います", id: "ada / mempunyai (makhluk hidup)" },
  { jp: "かかります", id: "memerlukan waktu / biaya" },
  { jp: "やすみます", id: "tidak masuk kerja / libur" },

  { jp: "ひとつ", id: "1 buah" },
  { jp: "ふたつ", id: "2 buah" },
  { jp: "みっつ", id: "3 buah" },
  { jp: "よっつ", id: "4 buah" },
  { jp: "いつつ", id: "5 buah" },
  { jp: "むっつ", id: "6 buah" },
  { jp: "ななつ", id: "7 buah" },
  { jp: "やっつ", id: "8 buah" },
  { jp: "ここのつ", id: "9 buah" },
  { jp: "とお", id: "10 buah" },
  { jp: "いくつ", id: "berapa buah?" },

  { jp: "ひとり", id: "1 orang" },
  { jp: "ふたり", id: "2 orang" },
  { jp: "~にん", id: "~ orang" },
  { jp: "~だい", id: "~ unit" },
  { jp: "~まい", id: "~ lembar" },
  { jp: "~かい", id: "~ kali" },

  { jp: "りんご", id: "apel" },
  { jp: "みかん", id: "jeruk" },
  { jp: "サンドイッチ", id: "sandwich" },
  { jp: "カレー", id: "kari" },
  { jp: "アイスクリーム", id: "es krim" },

  { jp: "きって", id: "perangko" },
  { jp: "はがき", id: "kartu pos" },
  { jp: "ふうとう", id: "amplop" },
  { jp: "がいこく", id: "luar negeri" },
  { jp: "りゅうがくせい", id: "pelajar asing" },
  { jp: "クラス", id: "kelas" },

  { jp: "~じかん", id: "~ jam" },
  { jp: "~しゅうかん", id: "~ minggu" },
  { jp: "~かげつ", id: "~ bulan" },
  { jp: "~ねん", id: "~ tahun" },
  { jp: "~ぐらい", id: "kira-kira ~" },
  { jp: "どのくらい", id: "berapa lama?" },

  { jp: "ぜんぶで", id: "semuanya" },
  { jp: "みんな", id: "semua orang" },
  { jp: "~だけ", id: "hanya ~" },

  { jp: "かしこまりました", id: "baik / mengerti" },
  { jp: "いいてんきですね", id: "cuacanya bagus ya" },
  { jp: "おでかけですか", id: "mau keluar?" },
  { jp: "いってらっしゃい", id: "hati-hati (berangkat)" },
  { jp: "いってきます", id: "saya berangkat" },

  { jp: "ふなびん", id: "pos laut" },
  { jp: "こうくうびん", id: "pos udara" },
  { jp: "エアメール", id: "pos udara" },

  { jp: "オーストラリア", id: "australia" },

  { jp: "ていしょく", id: "makanan paket" },
  { jp: "ランチ", id: "makan siang" },
  { jp: "てんどん", id: "nasi tempura" },
  { jp: "おやこどん", id: "nasi ayam dan telur" },
  { jp: "ぎゅうどん", id: "nasi daging sapi" },
  { jp: "やきにく", id: "daging panggang" },
  { jp: "やさいいため", id: "sayur goreng" },
  { jp: "つけもの", id: "asinan" },
  { jp: "みそしる", id: "sup miso" },
  { jp: "おにぎり", id: "nasi kepal" },
  { jp: "てんぷら", id: "tempura" },
  { jp: "すし", id: "sushi" },

  { jp: "うどん", id: "mi jepang besar" },
  { jp: "そば", id: "mi jepang abu-abu" },
  { jp: "ラーメン", id: "mi ramen" },
  { jp: "やきそば", id: "mi goreng jepang" },
  { jp: "おこのみやき", id: "gorengan adonan kol dan daging" },
  { jp: "カレーライス", id: "nasi kari" },
  { jp: "ハンバーグ", id: "hamburger steak" },
  { jp: "コロッケ", id: "kroket" },
  { jp: "えびフライ", id: "udang goreng tepung" },
  { jp: "フライドチキン", id: "ayam goreng" },
  { jp: "サラダ", id: "salad" },
  { jp: "スープ", id: "sup" },
  { jp: "スパゲッティ", id: "spageti" },
  { jp: "ピザ", id: "pizza" },
  { jp: "トースト", id: "roti panggang" },

  { jp: "コーヒー", id: "kopi" },
  { jp: "こうちゃ", id: "teh" },
  { jp: "ココア", id: "minuman coklat" },
  { jp: "ジュース", id: "jus" },
  { jp: "コーラ", id: "coca cola" }],
  12: [  { jp: "かんたん(な)", id: "mudah / gampang" },
  { jp: "ちかい", id: "dekat" },
  { jp: "とおい", id: "jauh" },
  { jp: "はやい", id: "cepat" },
  { jp: "おそい", id: "lambat" },
  { jp: "おおい", id: "banyak" },
  { jp: "すくない", id: "sedikit" },
  { jp: "あたたかい", id: "hangat" },
  { jp: "すずしい", id: "sejuk" },
  { jp: "あまい", id: "manis" },
  { jp: "からい", id: "pedas" },
  { jp: "おもい", id: "berat" },
  { jp: "かるい", id: "ringan" },
  { jp: "いい", id: "lebih baik" },

  { jp: "きせつ", id: "musim" },
  { jp: "てんき", id: "cuaca" },
  { jp: "あめ", id: "hujan" },
  { jp: "ゆき", id: "salju" },
  { jp: "くもり", id: "mendung" },

  { jp: "ホテル", id: "hotel" },
  { jp: "くうこう", id: "bandara" },
  { jp: "うみ", id: "laut" },
  { jp: "せかい", id: "dunia" },
  { jp: "パーティー", id: "pesta" },
  { jp: "まつり", id: "perayaan" },
  { jp: "レモン", id: "lemon" },
  { jp: "いけばな", id: "seni merangkai bunga" },
  { jp: "もみじ", id: "daun maple" },

  { jp: "どちら", id: "yang mana" },
  { jp: "どちらも", id: "dua-duanya" },
  { jp: "いちばん", id: "yang paling" },
  { jp: "ずっと", id: "selamanya" },
  { jp: "はじめて", id: "pertama kali" },

  { jp: "ただいま", id: "saya pulang" },
  { jp: "おかえりなさい", id: "sudah pulang ya" },
  { jp: "わあ、すごいひとですね", id: "wah, banyak orang ya" },
  { jp: "つかれました", id: "capek / lelah" },

  { jp: "ホンコン", id: "hongkong" },
  { jp: "シンガポール", id: "singapura" },
  { jp: "めいしょ", id: "tempat terkenal" }],
  13: [{ jp: "あそびます", id: "bermain" },
  { jp: "およぎます", id: "berenang" },
  { jp: "むかえます", id: "menjemput" },
  { jp: "つかれます", id: "lelah" },
  { jp: "けっこんします", id: "menikah" },
  { jp: "かいものします", id: "berbelanja" },
  { jp: "しょくじします", id: "makan bersama" },
  { jp: "さんぽします", id: "jalan-jalan" },

  { jp: "たいへん(な)", id: "susah / berat" },
  { jp: "ほしい", id: "ingin" },
  { jp: "ひろい", id: "luas" },
  { jp: "せまい", id: "sempit" },

  { jp: "プール", id: "kolam renang" },
  { jp: "かわ", id: "sungai" },
  { jp: "びじゅつ", id: "seni" },
  { jp: "つり", id: "memancing" },
  { jp: "スキー", id: "ski" },
  { jp: "しゅうまつ", id: "akhir pekan" },
  { jp: "おしょうがつ", id: "tahun baru" },

  { jp: "~ごろ", id: "kira-kira / sekitar" },
  { jp: "なにか", id: "sesuatu" },
  { jp: "どこか", id: "suatu tempat" },

  { jp: "のどがかわきます", id: "haus" },
  { jp: "おなかがすきます", id: "lapar" },
  { jp: "そうしましょう", id: "ya, ayo" },

  { jp: "ごちゅうもんは", id: "mau pesan apa?" },
  { jp: "おまちください", id: "tunggu sebentar" },
  { jp: "べつべつに", id: "sendiri-sendiri / masing-masing" },

  { jp: "はくぶつかん", id: "museum" },
  { jp: "びじゅつかん", id: "gedung kesenian" },
  { jp: "としょかん", id: "perpustakaan" },
  { jp: "えいがかん", id: "bioskop" },
  { jp: "どうぶつえん", id: "kebun binatang" },
  { jp: "しょくぶつえん", id: "kebun raya" },
  { jp: "おてら", id: "kuil buddha" },
  { jp: "じんじゃ", id: "kuil shinto" },
  { jp: "きょうかい", id: "gereja" },
  { jp: "たいしかん", id: "kedutaan besar" },
  { jp: "にゅうこくかんりきょく", id: "kantor imigrasi" },
  { jp: "しやくしょ", id: "kantor balai kota" },
  { jp: "こうばん", id: "pos polisi" },
  { jp: "ちゅうしゃじょう", id: "tempat parkir" },

  { jp: "だいがく", id: "universitas" },
  { jp: "こうこう", id: "SMA" },
  { jp: "ちゅうがっこう", id: "SMP" },
  { jp: "しょうがっこう", id: "SD" },
  { jp: "ようちえん", id: "TK" },

  { jp: "にくや", id: "toko daging" },
  { jp: "パンや", id: "toko roti" },
  { jp: "さかなや", id: "toko ikan" },
  { jp: "やおや", id: "toko sayuran" }],
  14: [ { jp: "つけます", id: "menyalakan / memasang" },
  { jp: "けします", id: "mematikan / memadamkan" },
  { jp: "あけます", id: "membuka" },
  { jp: "しめます", id: "menutup" },
  { jp: "いそぎます", id: "buru-buru" },
  { jp: "まちます", id: "menunggu" },
  { jp: "もちます", id: "membawa" },
  { jp: "とります", id: "mengambil" },
  { jp: "てつだいます", id: "membantu" },
  { jp: "よびます", id: "memanggil" },
  { jp: "はなします", id: "berbicara" },
  { jp: "つかいます", id: "memakai" },
  { jp: "とめます", id: "menghentikan" },
  { jp: "みせます", id: "memperlihatkan" },
  { jp: "おしえます", id: "memberitahu" },
  { jp: "すわります", id: "duduk" },
  { jp: "たちます", id: "berdiri" },
  { jp: "はいります", id: "masuk" },
  { jp: "でます", id: "keluar" },
  { jp: "ふります", id: "turun hujan" },

  { jp: "コピーします", id: "memfotokopi" },

  { jp: "でんき", id: "listrik / lampu" },
  { jp: "エアコン", id: "AC" },
  { jp: "パスポート", id: "paspor" },
  { jp: "なまえ", id: "nama" },
  { jp: "じゅうしょ", id: "alamat" },
  { jp: "ちず", id: "peta" },
  { jp: "しお", id: "garam" },
  { jp: "さとう", id: "gula" },

  { jp: "もんだい", id: "masalah / soal" },
  { jp: "こたえ", id: "jawaban" },
  { jp: "よみかた", id: "cara membaca" },
  { jp: "~かた", id: "cara ~" },

  { jp: "まっすぐ", id: "lurus" },
  { jp: "ゆっくり", id: "pelan-pelan" },
  { jp: "すぐ", id: "segera" },
  { jp: "また", id: "lagi" },
  { jp: "あとで", id: "nanti" },
  { jp: "もうすこし", id: "sedikit lagi" },
  { jp: "もう~", id: "~ lagi" },
  { jp: "さあ", id: "ayo" },
  { jp: "あれ？", id: "loh? / ah?" },

  { jp: "これでおねがいします", id: "minta dengan ini" },
  { jp: "おつり", id: "kembalian" },

  { jp: "きっぷうりば", id: "loket karcis" },
  { jp: "じどうけんばいき", id: "mesin karcis otomatis" },
  { jp: "せいさんき", id: "mesin penghitungan otomatis" },
  { jp: "かいさつぐち", id: "pintu pemeriksaan karcis" },
  { jp: "でぐち", id: "pintu keluar" },
  { jp: "いりぐち", id: "pintu masuk" },
  { jp: "ひがしぐち", id: "pintu timur" },
  { jp: "にしぐち", id: "pintu barat" },
  { jp: "みなみぐち", id: "pintu selatan" },
  { jp: "きたぐち", id: "pintu utara" },
  { jp: "ちゅうおうぐち", id: "pintu tengah" },

  { jp: "プラットホーム", id: "peron" },
  { jp: "ばいてん", id: "kios" },
  { jp: "コインロッカー", id: "loker" },
  { jp: "タクシーのりば", id: "tempat naik taksi" },
  { jp: "バスターミナル", id: "terminal bus" },
  { jp: "バスてい", id: "halte bus" },

  { jp: "かいそく", id: "kereta cepat" },
  { jp: "じゅんきゅう", id: "kereta semi cepat" },
  { jp: "じこくひょう", id: "jadwal keberangkatan" },
  { jp: "~はつ", id: "berangkat dari / pukul" },
  { jp: "~ちゃく", id: "tiba di / pukul" },
  { jp: "とうきょういき", id: "tujuan tokyo" },
  { jp: "ていきけん", id: "kartu langganan" },
  { jp: "かいすうけん", id: "karcis kupon" },
  { jp: "かたみち", id: "sekali jalan" },
  { jp: "おうふく", id: "pulang pergi" }],
  15: [ { jp: "おきます", id: "meletakkan" },
  { jp: "つくります", id: "membuat" },
  { jp: "うります", id: "menjual" },
  { jp: "しります", id: "mengetahui / mengenal" },
  { jp: "すみます", id: "tinggal" },
  { jp: "けんきゅうします", id: "meneliti" },

  { jp: "しりょう", id: "data / bahan" },
  { jp: "カタログ", id: "katalog" },
  { jp: "ふく", id: "pakaian" },
  { jp: "せいひん", id: "produk" },
  { jp: "ソフト", id: "perangkat lunak" },
  { jp: "でんしじしょ", id: "kamus elektronik" },
  { jp: "けいざい", id: "ekonomi" },
  { jp: "はいしゃ", id: "dokter gigi" },
  { jp: "どくしん", id: "bujangan / jomblo" },
  { jp: "おもいだします", id: "teringat" },

  { jp: "いらっしゃいます", id: "ada (orang hidup, sopan)" },

  { jp: "しょくぎょう", id: "pekerjaan / profesi" },
  { jp: "かいしゃいん", id: "pegawai perusahaan" },
  { jp: "こうむいん", id: "pegawai negeri" },
  { jp: "えきいん", id: "pegawai stasiun" },
  { jp: "ぎんこういん", id: "pegawai bank" },
  { jp: "ゆうびんきょくいん", id: "pegawai kantor pos" },
  { jp: "てんいん", id: "pegawai toko" },
  { jp: "ちょうりし", id: "tukang masak" },
  { jp: "りようし", id: "tukang potong rambut" },
  { jp: "びようし", id: "ahli kecantikan" },
  { jp: "きょうし", id: "guru" },
  { jp: "べんごし", id: "pengacara" },
  { jp: "けんきゅうしゃ", id: "peneliti" },
  { jp: "いしゃ", id: "dokter" },
  { jp: "かんごし", id: "perawat" },
  { jp: "うんてんしゅ", id: "sopir" },

  { jp: "けいさつかん", id: "polisi" },
  { jp: "がいこうかん", id: "diplomat" },
  { jp: "せいじか", id: "politikus" },
  { jp: "がか", id: "pelukis" },
  { jp: "さっか", id: "pengarang" },
  { jp: "おんがくか", id: "musisi" },
  { jp: "けんちくか", id: "arsitek" },
  { jp: "エンジニア", id: "insinyur" },
  { jp: "デザイナー", id: "desainer" },
  { jp: "ジャーナリスト", id: "wartawan" },
  { jp: "かしゅ", id: "penyanyi" },
  { jp: "はいゆう", id: "aktor / artis" },
  { jp: "スポーツせんしゅ", id: "olahragawan / atlet" }],

  16: [{ jp: "のります", id: "naik" },
  { jp: "おります", id: "turun" },
  { jp: "のりかえます", id: "ganti / pindah kendaraan" },
  { jp: "あびます", id: "mandi" },
  { jp: "いれます", id: "memasukkan" },
  { jp: "だします", id: "mengeluarkan" },
  { jp: "おろします", id: "menarik / mengambil uang" },
  { jp: "はいります", id: "masuk" },
  { jp: "でます", id: "keluar" },
  { jp: "おします", id: "menekan" },
  { jp: "のみます", id: "minum" },
  { jp: "はじめます", id: "mulai" },
  { jp: "けんがくします", id: "mengunjungi / studi banding" },
  { jp: "でんわします", id: "menelepon" },

  { jp: "わかい", id: "muda" },
  { jp: "ながい", id: "panjang" },
  { jp: "みじかい", id: "pendek" },
  { jp: "あかるい", id: "terang" },
  { jp: "くらい", id: "gelap" },

  { jp: "からだ", id: "badan" },
  { jp: "あたま", id: "kepala" },
  { jp: "かみ", id: "rambut" },
  { jp: "かお", id: "wajah" },
  { jp: "め", id: "mata" },
  { jp: "みみ", id: "telinga" },
  { jp: "はな", id: "hidung" },
  { jp: "くち", id: "mulut" },
  { jp: "は", id: "gigi" },
  { jp: "おなか", id: "perut" },
  { jp: "あし", id: "kaki" },
  { jp: "せ", id: "punggung" },

  { jp: "サービス", id: "pelayanan" },
  { jp: "ジョギング", id: "joging" },
  { jp: "シャワー", id: "shower" },
  { jp: "みどり", id: "hijau" },
  { jp: "おてら", id: "kuil" },
  { jp: "じんじゃ", id: "kuil shinto" },

  { jp: "~ばん", id: "nomor" },
  { jp: "どうやって", id: "bagaimana caranya" },
  { jp: "どの~", id: "yang mana" },
  { jp: "どれ", id: "yang mana" },
  { jp: "すごいですね", id: "hebat ya" },
  { jp: "いいえ、まだまだです", id: "tidak, belum seberapa" },

  { jp: "おひきだし", id: "penarikan uang" },
  { jp: "まず", id: "pertama-tama" },
  { jp: "つぎに", id: "kemudian" },
  { jp: "キャッシュカード", id: "kartu ATM" },
  { jp: "あんしょうばんごう", id: "PIN" },
  { jp: "きんがく", id: "jumlah uang" },
  { jp: "かくにん", id: "konfirmasi" },
  { jp: "ボタン", id: "tombol" },

  { jp: "ゆきまつり", id: "festival salju" },
  { jp: "おあずけいれ", id: "setor saldo" },
  { jp: "おふりこみ", id: "transfer / pembayaran" },
  { jp: "おふりかえ", id: "pemindahan dana" },
  { jp: "つうちょうきにゅう", id: "pembaruan buku tabungan" },
  { jp: "ざんだかしょうかい", id: "cek saldo" }],
  17: [ { jp: "おぼえます", id: "mengingat" },
  { jp: "わすれます", id: "lupa" },
  { jp: "なくします", id: "kehilangan" },
  { jp: "はらいます", id: "membayar" },
  { jp: "かえします", id: "mengembalikan" },
  { jp: "でかけます", id: "keluar rumah" },
  { jp: "ぬぎます", id: "melepas pakaian" },
  { jp: "もっていきます", id: "membawa pergi" },
  { jp: "もってきます", id: "membawa datang" },
  { jp: "しんぱいします", id: "khawatir" },
  { jp: "ざんぎょうします", id: "lembur" },
  { jp: "しゅっちょうします", id: "dinas" },

  { jp: "たいせつな", id: "penting" },
  { jp: "だいじょうぶな", id: "tidak apa-apa" },
  { jp: "あぶない", id: "berbahaya" },
  { jp: "きんえん", id: "dilarang merokok" },

  { jp: "けんこうほけんしょう", id: "kartu asuransi kesehatan" },
  { jp: "ねつ", id: "demam" },
  { jp: "びょうき", id: "sakit" },
  { jp: "くすり", id: "obat" },
  { jp: "おふろ", id: "kamar mandi" },
  { jp: "うわぎ", id: "jaket / baju luar" },
  { jp: "したぎ", id: "pakaian dalam" },

  { jp: "までに", id: "sampai dengan (batas waktu)" },
  { jp: "ですから", id: "oleh karena itu" },
  { jp: "どうしましたか", id: "ada apa?" },

  { jp: "のど", id: "tenggorokan" },
  { jp: "いたい", id: "sakit / nyeri" },
  { jp: "かぜ", id: "masuk angin" },
  { jp: "それから", id: "setelah itu" },

  { jp: "おだいじに", id: "semoga lekas sembuh" },
  { jp: "あたまがいたい", id: "sakit kepala" },
  { jp: "おなかがいたい", id: "sakit perut" },
  { jp: "はがいたい", id: "sakit gigi" },
  { jp: "ねつがあります", id: "demam" },
  { jp: "せきがでます", id: "batuk" },
  { jp: "はなみずがでます", id: "pilek" },
  { jp: "ちがでます", id: "berdarah" },
  { jp: "はきけがします", id: "mual" },
  { jp: "さむけがします", id: "menggigil" },
  { jp: "めまいがします", id: "pusing" },
  { jp: "げりをします", id: "diare" },
  { jp: "べんぴをします", id: "sembelit" },
  { jp: "けがをします", id: "terluka" },
  { jp: "やけどをします", id: "terbakar" },
  { jp: "しょくよくがありません", id: "tidak nafsu makan" },
  { jp: "かたがこります", id: "bahu pegal" },
  { jp: "からだがだるい", id: "badan lemas" },
  { jp: "かゆい", id: "gatal" },

  { jp: "インフルエンザ", id: "influenza" },
  { jp: "もうちょう", id: "usus buntu" },
  { jp: "ぎっくりごし", id: "sakit pinggang" },
  { jp: "ねんざ", id: "keseleo" },
  { jp: "こっせつ", id: "patah tulang" },
  { jp: "ふつかよい", id: "hangover" }],
  18: [  { jp: "できます", id: "bisa / mampu" },
  { jp: "あらいます", id: "mencuci" },
  { jp: "ひきます", id: "memainkan (alat musik)" },
  { jp: "うたいます", id: "menyanyi" },
  { jp: "あつめます", id: "mengumpulkan" },
  { jp: "すてます", id: "membuang" },
  { jp: "かえます", id: "menukar / mengganti" },
  { jp: "うんてんします", id: "menyetir / mengemudi" },
  { jp: "よやくします", id: "memesan / reservasi" },

  { jp: "ピアノ", id: "piano" },
  { jp: "~メートル", id: "meter" },
  { jp: "げんきん", id: "uang tunai" },
  { jp: "しゅみ", id: "hobi" },
  { jp: "にっき", id: "buku harian" },
  { jp: "おいのり", id: "doa" },

  { jp: "かちょう", id: "kepala seksi" },
  { jp: "ぶちょう", id: "kepala bagian" },
  { jp: "しゃちょう", id: "direktur utama" },

  { jp: "どうぶつ", id: "hewan" },
  { jp: "うま", id: "kuda" },
  { jp: "インターネット", id: "internet" },

  { jp: "とくに", id: "terutama" },
  { jp: "それはおもしろいですね", id: "itu menarik ya" },
  { jp: "ほんとうですか", id: "benarkah?" },
  { jp: "ぜひ", id: "pasti / sangat ingin" },

  { jp: "なかなか", id: "tidak mudah / jarang" },

  { jp: "とぶ", id: "terbang / meloncat" },
  { jp: "のぼる", id: "memanjat" },
  { jp: "はしる", id: "berlari" },
  { jp: "およぐ", id: "berenang" },
  { jp: "もぐる", id: "menyelam" },
  { jp: "とびこむ", id: "terjun" },
  { jp: "さかだちする", id: "berjungkir balik" },
  { jp: "はう", id: "merayap" },
  { jp: "ける", id: "menendang" },
  { jp: "ふる", id: "melambaikan" },
  { jp: "もちあげる", id: "mengangkat" },
  { jp: "なげる", id: "melempar" },
  { jp: "たたく", id: "memukul" },
  { jp: "ひく", id: "menarik" },
  { jp: "おす", id: "mendorong / menekan" },
  { jp: "まげる", id: "membengkokkan" },
  { jp: "のばす", id: "meluruskan" },
  { jp: "ころぶ", id: "jatuh" },
  { jp: "ふりむく", id: "menoleh ke belakang" }],
  19: [{ jp: "のぼります", id: "naik / mendaki" },
  { jp: "とまります", id: "menginap" },
  { jp: "そうじします", id: "membersihkan" },
  { jp: "せんたくします", id: "mencuci pakaian" },
  { jp: "なります", id: "menjadi" },

  { jp: "ねむい", id: "mengantuk" },
  { jp: "つよい", id: "kuat" },
  { jp: "よわい", id: "lemah" },

  { jp: "れんしゅう", id: "latihan" },
  { jp: "ゴルフ", id: "golf" },
  { jp: "すもう", id: "sumo" },
  { jp: "おちゃ", id: "teh" },
  { jp: "ひ", id: "hari" },
  { jp: "ちょうし", id: "kondisi" },

  { jp: "いちど", id: "sekali" },
  { jp: "いちども", id: "sekalipun" },
  { jp: "だんだん", id: "berangsur-angsur" },
  { jp: "もうすぐ", id: "sebentar lagi" },
  { jp: "おかげさまで", id: "berkat anda" },
  { jp: "でも", id: "tetapi" },

  { jp: "かんぱい", id: "bersulang" },
  { jp: "ダイエット", id: "diet" },
  { jp: "むりな", id: "berlebihan / tidak mungkin" },
  { jp: "からだにいい", id: "baik untuk tubuh" },

  { jp: "とうきょうスカイツリー", id: "tokyo skytree" },
  { jp: "さどう", id: "upacara minum teh" },
  { jp: "かどう", id: "seni merangkai bunga" },
  { jp: "しょどう", id: "seni menulis jepang" },
  { jp: "かぶき", id: "kabuki" },
  { jp: "のう", id: "noh" },
  { jp: "ぶんらく", id: "bunraku" },
  { jp: "じゅうどう", id: "judo" },
  { jp: "けんどう", id: "kendo" },
  { jp: "からて", id: "karate" },
  { jp: "まんざい・らくご", id: "komedi jepang" },
  { jp: "いご・しょうぎ", id: "catur jepang" },
  { jp: "パチンコ", id: "pachinko" },
  { jp: "カラオケ", id: "karaoke" },
  { jp: "ぼんおどり", id: "tarian bon" }],
  20: [{ jp: "いります", id: "memerlukan" },
  { jp: "しらべます", id: "mengecek / meneliti" },
  { jp: "しゅうりします", id: "memperbaiki" },

  { jp: "ぼく", id: "aku (laki-laki)" },
  { jp: "きみ", id: "kamu" },
  { jp: "~くん", id: "saudara ~ (panggilan)" },

  { jp: "うん", id: "ya" },
  { jp: "ううん", id: "tidak" },

  { jp: "ことば", id: "kata / bahasa" },
  { jp: "きもの", id: "kimono" },
  { jp: "ビザ", id: "visa" },
  { jp: "はじめ", id: "awal" },
  { jp: "おわり", id: "akhir" },

  { jp: "こっち", id: "sini" },
  { jp: "そっち", id: "situ" },
  { jp: "あっち", id: "sana" },
  { jp: "どっち", id: "yang mana" },

  { jp: "みんなで", id: "kita semua" },
  { jp: "~けど", id: "tetapi" },
  { jp: "おなかがいっぱいです", id: "kenyang" },
  { jp: "よかったら", id: "kalau mau / kalau suka" },
  { jp: "いろいろ", id: "macam-macam" }],

  21: [ { jp: "おもいます", id: "berpikir / mengira" },
  { jp: "いいます", id: "mengatakan" },
  { jp: "かちます", id: "menang" },
  { jp: "まけます", id: "kalah" },
  { jp: "やくにたちます", id: "berguna" },
  { jp: "うごきます", id: "bergerak" },
  { jp: "やめます", id: "berhenti" },
  { jp: "きをつけます", id: "berhati-hati" },
  { jp: "りゅうがくします", id: "studi ke luar negeri" },
  { jp: "むだな", id: "sia-sia" },
  { jp: "ふべんな", id: "tidak praktis" },

  { jp: "すごい", id: "hebat" },
  { jp: "ほんとう", id: "benar" },
  { jp: "うそ", id: "bohong" },
  { jp: "じどうしゃ", id: "mobil" },
  { jp: "こうつう", id: "lalu lintas" },
  { jp: "ぶっか", id: "harga barang" },
  { jp: "ニュース", id: "berita" },
  { jp: "アニメ", id: "animasi" },
  { jp: "マンガ", id: "komik" },
  { jp: "デザイン", id: "desain" },
  { jp: "ゆめ", id: "mimpi" },
  { jp: "てんさい", id: "jenius" },
  { jp: "しあい", id: "pertandingan" },
  { jp: "いけん", id: "pendapat" },
  { jp: "はなし", id: "cerita" },

  { jp: "さいきん", id: "akhir-akhir ini" },
  { jp: "たぶん", id: "mungkin" },
  { jp: "きっと", id: "pasti" },
  { jp: "ほんとうに", id: "benar-benar" },
  { jp: "そんなに", id: "tidak begitu" },
  { jp: "~について", id: "tentang" },
  { jp: "ひさしぶりですね", id: "lama tidak bertemu" },
  { jp: "もちろん", id: "tentu saja" }],
  22: [ { jp: "きます", id: "memakai (baju)" },
  { jp: "はきます", id: "memakai (celana/sepatu)" },
  { jp: "かぶります", id: "memakai (topi)" },
  { jp: "かけます", id: "memakai (kacamata)" },
  { jp: "します", id: "memakai (dasi)" },
  { jp: "うまれます", id: "lahir" },
  { jp: "わたしたち", id: "kami / kita" },

  { jp: "コート", id: "mantel" },
  { jp: "セーター", id: "sweter" },
  { jp: "スーツ", id: "setelan" },
  { jp: "ぼうし", id: "topi" },
  { jp: "めがね", id: "kacamata" },
  { jp: "ケーキ", id: "kue" },
  { jp: "おべんとう", id: "bekal" },
  { jp: "ロボット", id: "robot" },
  { jp: "ユーモア", id: "humor" },

  { jp: "よく", id: "sering" },
  { jp: "おめでとうございます", id: "selamat" },
  { jp: "では", id: "kalau begitu" },

  { jp: "やちん", id: "uang sewa" },
  { jp: "わしつ", id: "kamar ala jepang" },
  { jp: "ふとん", id: "kasur jepang" },

  { jp: "ワンピース", id: "gaun terusan" },
  { jp: "ジーンズ", id: "celana jeans" },
  { jp: "スカート", id: "rok" },
  { jp: "くつした", id: "kaos kaki" }],
  23: [{ jp: "ききます", id: "bertanya" },
  { jp: "まわします", id: "memutar" },
  { jp: "ひきます", id: "menarik" },
  { jp: "かえます", id: "mengubah" },
  { jp: "さわります", id: "menyentuh" },
  { jp: "あるきます", id: "berjalan" },
  { jp: "わたります", id: "menyeberang" },
  { jp: "まがります", id: "belok" },

  { jp: "さびしい", id: "sepi" },
  { jp: "おゆ", id: "air panas" },
  { jp: "おと", id: "suara" },
  { jp: "サイズ", id: "ukuran" },
  { jp: "こしょう", id: "kerusakan" },

  { jp: "みち", id: "jalan" },
  { jp: "こうさてん", id: "perempatan" },
  { jp: "しんごう", id: "lampu lalu lintas" },
  { jp: "はし", id: "jembatan" },
  { jp: "ちゅうしゃじょう", id: "tempat parkir" },

  { jp: "とまれ", id: "berhenti" },
  { jp: "ちゅうしゃきんし", id: "dilarang parkir" }],
  24: [{ jp: "くれます", id: "memberi (kepada saya)" },
  { jp: "なおします", id: "memperbaiki" },
  { jp: "つれていきます", id: "mengajak pergi" },
  { jp: "つれてきます", id: "membawa datang" },
  { jp: "おくります", id: "mengantar" },
  { jp: "しょうかいします", id: "memperkenalkan" },
  { jp: "あんないします", id: "memandu" },
  { jp: "せつめいします", id: "menjelaskan" },

  { jp: "じゅんび", id: "persiapan" },
  { jp: "ひっこし", id: "pindah rumah" },
  { jp: "おかし", id: "snack" },
  { jp: "ホームステイ", id: "homestay" },
  { jp: "ぜんぶ", id: "semua" },
  { jp: "じぶんで", id: "sendiri" }],
  25: [{ jp: "かんがえます", id: "memikirkan" },
  { jp: "つきます", id: "tiba" },
  { jp: "とります", id: "berumur" },
  { jp: "たります", id: "cukup" },

  { jp: "いなか", id: "desa / kampung halaman" },
  { jp: "チャンス", id: "kesempatan" },
  { jp: "もし", id: "kalau" },
  { jp: "いみ", id: "arti" },

  { jp: "がんばります", id: "berusaha keras" },
  { jp: "どうぞおげんきで", id: "semoga sehat selalu" }],

  26: [{ jp: "みます", id: "melihat / memeriksa" },
  { jp: "さがします", id: "mencari" },
  { jp: "おくれます", id: "terlambat" },
  { jp: "まにあいます", id: "tepat waktu" },
  { jp: "やります", id: "melakukan" },
  { jp: "さんかします", id: "ikut serta" },
  { jp: "もうしこみます", id: "mendaftar" },

  { jp: "つごうがいい", id: "tidak ada halangan" },
  { jp: "つごうがわるい", id: "ada halangan" },
  { jp: "きぶんがいい", id: "perasaan enak" },
  { jp: "きぶんがわるい", id: "tidak enak badan" },

  { jp: "しんぶんしゃ", id: "perusahaan surat kabar" },
  { jp: "うんどうかい", id: "pesta olahraga" },
  { jp: "ばしょ", id: "tempat" },
  { jp: "ボランティア", id: "sukarelawan" },

  { jp: "こんど", id: "lain kali" },
  { jp: "ずいぶん", id: "cukup / lumayan" },
  { jp: "ちょくせつ", id: "langsung" },
  { jp: "いつでも", id: "kapan pun" },
  { jp: "どこでも", id: "di mana pun" },
  { jp: "だれでも", id: "siapa pun" },
  { jp: "なんでも", id: "apa pun" }],
  27: [  { jp: "かいます", id: "memelihara (hewan)" },
  { jp: "たてます", id: "membangun" },
  { jp: "はしります", id: "berlari" },
  { jp: "とります", id: "mengambil / cuti" },
  { jp: "みえます", id: "terlihat" },
  { jp: "きこえます", id: "terdengar" },
  { jp: "できます", id: "selesai / jadi" },
  { jp: "ひらきます", id: "membuka" },

  { jp: "ペット", id: "hewan peliharaan" },
  { jp: "とり", id: "burung" },
  { jp: "こえ", id: "suara" },
  { jp: "なみ", id: "ombak" },
  { jp: "はなび", id: "kembang api" },
  { jp: "けしき", id: "pemandangan" },

  { jp: "むかし", id: "zaman dahulu" },
  { jp: "どうぐ", id: "alat" },
  { jp: "マンション", id: "apartemen" },
  { jp: "だいどころ", id: "dapur" },

  { jp: "ゆめ", id: "mimpi" },
  { jp: "いつか", id: "suatu hari" },
  { jp: "すばらしい", id: "luar biasa" }],
  28: [  { jp: "うれます", id: "terjual" },
  { jp: "おどります", id: "menari" },
  { jp: "かみます", id: "mengunyah / menggigit" },
  { jp: "えらびます", id: "memilih" },
  { jp: "ちがいます", id: "berbeda" },
  { jp: "かよいます", id: "pulang pergi" },
  { jp: "メモします", id: "mencatat" },

  { jp: "まじめな", id: "rajin / serius" },
  { jp: "ねっしんな", id: "tekun" },
  { jp: "やさしい", id: "lembut / baik" },
  { jp: "えらい", id: "hebat" },
  { jp: "ちょうどいい", id: "pas" },

  { jp: "けいけん", id: "pengalaman" },
  { jp: "きゅうりょう", id: "gaji" },
  { jp: "ボーナス", id: "bonus" },
  { jp: "ばんぐみ", id: "acara TV" },

  { jp: "しばらく", id: "sebentar / sementara" },
  { jp: "たいてい", id: "biasanya" }],
  29: [  { jp: "あきます", id: "terbuka" },
  { jp: "しまります", id: "tertutup" },
  { jp: "つきます", id: "menyala" },
  { jp: "きえます", id: "padam" },
  { jp: "こみます", id: "ramai / macet" },
  { jp: "すきます", id: "sepi" },
  { jp: "こわれます", id: "rusak" },
  { jp: "われます", id: "pecah" },
  { jp: "おれます", id: "patah" },
  { jp: "やぶれます", id: "sobek" },

  { jp: "よごれます", id: "menjadi kotor" },
  { jp: "とまります", id: "berhenti" },
  { jp: "まちがえます", id: "salah" },
  { jp: "おとします", id: "menjatuhkan" },

  { jp: "さいふ", id: "dompet" },
  { jp: "ポケット", id: "saku" },
  { jp: "じしん", id: "gempa" },
  { jp: "かべ", id: "dinding" }],
  30: [{ jp: "はります", id: "menempelkan" },
  { jp: "かけます", id: "menggantungkan" },
  { jp: "かざります", id: "menghias" },
  { jp: "ならべます", id: "menyusun rapi" },
  { jp: "うえます", id: "menanam" },
  { jp: "もどします", id: "mengembalikan" },
  { jp: "まとめます", id: "merangkum / menyatukan" },
  { jp: "かたづけます", id: "membereskan" },
  { jp: "しまいます", id: "menyimpan" },
  { jp: "きめます", id: "menentukan" },

  { jp: "しらせます", id: "memberitahu" },
  { jp: "そうだんします", id: "berkonsultasi" },
  { jp: "よしゅうします", id: "belajar duluan" },
  { jp: "ふくしゅうします", id: "mengulang pelajaran" },

  { jp: "よてい", id: "rencana" },
  { jp: "カレンダー", id: "kalender" },
  { jp: "ポスター", id: "poster" },
  { jp: "ごみばこ", id: "tempat sampah" }],

  31: [{ jp: "はじまります", id: "mulai, dimulai" },
  { jp: "つづけます", id: "meneruskan, melanjutkan" },
  { jp: "みつけます", id: "menemukan" },
  { jp: "うけます", id: "menempuh, mengikuti (ujian)" },
  { jp: "にゅうがくします", id: "masuk universitas" },
  { jp: "そつぎょうします", id: "lulus universitas" },
  { jp: "しゅっせきします", id: "menghadiri" },
  { jp: "きゅうけいします", id: "beristirahat" },
  { jp: "れんきゅう", id: "libur berurutan" },
  { jp: "さくぶん", id: "karangan" },
  { jp: "てんらんかい", id: "pameran" },
  { jp: "けっこんしき", id: "upacara perkawinan" },
  { jp: "おそうしき", id: "upacara kematian" },
  { jp: "しき", id: "upacara" },
  { jp: "ほんしゃ", id: "kantor pusat" },
  { jp: "してん", id: "kantor cabang" },
  { jp: "きょうかい", id: "gereja" },
  { jp: "だいがくいん", id: "pasca sarjana" },
  { jp: "どうぶつえん", id: "kebun binatang" },
  { jp: "おんせん", id: "pemandian air panas" },
  { jp: "おきゃく", id: "tamu, pelanggan" },
  { jp: "だれか", id: "seseorang" },
  { jp: "~のほう", id: "bagian (tempat)" },
  { jp: "ずっと", id: "terus menerus, selamanya" },
  { jp: "のこります", id: "tinggal, tersisa" },
  { jp: "つきに", id: "per bulan" },
  { jp: "ふつうの", id: "biasa, umum" },
  { jp: "インターネット", id: "internet" },
  { jp: "むら", id: "desa" },
  { jp: "えいがかん", id: "bioskop" },
  { jp: "そら", id: "langit" },
  { jp: "とじます", id: "menutup, memejamkan" },
  { jp: "とかい", id: "kota besar" },
  { jp: "こどもたち", id: "anak-anak" },
  { jp: "じゆうに", id: "dengan bebas" },
  { jp: "せかいじゅう", id: "seluruh dunia" },
  { jp: "あつまります", id: "berkumpul" },
  { jp: "うつくしい", id: "indah" },
  { jp: "しぜん", id: "alam" },
  { jp: "すばらしさ", id: "keindahan, kebaikan" },
  { jp: "きがつきます", id: "menyadari" },
  { jp: "せんもん", id: "bidang keahlian" },
  { jp: "いがく", id: "kedokteran" },
  { jp: "やくがく", id: "farmasi" },
  { jp: "かがく", id: "kimia" },
  { jp: "せいかがく", id: "biokimia" },
  { jp: "せいぶつがく", id: "biologi" },
  { jp: "のうがく", id: "pertanian" },
  { jp: "ちがく", id: "geologi" },
  { jp: "ちりがく", id: "geografi" },
  { jp: "すうがく", id: "matematika" },
  { jp: "ぶつりがく", id: "fisika" },
  { jp: "こうがく", id: "teknik" },
  { jp: "どぼくこうがく", id: "teknik sipil" },
  { jp: "でんしこうがく", id: "elektronika" },
  { jp: "でんきこうがく", id: "teknik listrik" },
  { jp: "きかいこうがく", id: "teknik mesin" },
  { jp: "コンピューターこうがく", id: "informatika" },
  { jp: "いでんしこうがく", id: "genetika" },
  { jp: "けんちくがく", id: "arsitektur" },
  { jp: "てんもんがく", id: "astronomi" },
  { jp: "かんきょうかがく", id: "ilmu lingkungan" },
  { jp: "せいじがく", id: "ilmu politik" },
  { jp: "こくさいかんけいがく", id: "hubungan internasional" },
  { jp: "ほうりつがく", id: "hukum" },
  { jp: "けいざいがく", id: "ekonomi" },
  { jp: "けいえいがく", id: "manajemen bisnis" },
  { jp: "しゃかいがく", id: "sosiologi" },
  { jp: "きょういくがく", id: "pendidikan" },
  { jp: "ぶんがく", id: "sastra" },
  { jp: "げんごがく", id: "linguistik" },
  { jp: "しんりがく", id: "psikologi" },
  { jp: "てつがく", id: "filsafat" },
  { jp: "しゅうきょうがく", id: "teologi" },
  { jp: "げいじゅつ", id: "seni" },
  { jp: "びじゅつ", id: "seni murni" },
  { jp: "おんがく", id: "seni musik" },
  { jp: "たいいくがく", id: "pendidikan jasmani" }],
  32: [{ jp: "うんどうします", id: "berolahraga" },
  { jp: "せいこうします", id: "berhasil" },
  { jp: "しっぱいします", id: "gagal" },
  { jp: "ごうかくします", id: "lulus" },
  { jp: "もどります", id: "kembali" },
  { jp: "やみます", id: "berhenti (hujan)" },
  { jp: "はれます", id: "menjadi cerah" },
  { jp: "くもります", id: "menjadi mendung" },
  { jp: "ふきます", id: "angin bertiup" },
  { jp: "なおります", id: "sembuh / diperbaiki" },
  { jp: "つづきます", id: "berlanjut" },
  { jp: "ひきます", id: "masuk angin" },
  { jp: "ひやします", id: "mendinginkan" },
  { jp: "しんぱいな", id: "khawatir" },
  { jp: "じゅうぶんな", id: "cukup" },
  { jp: "おかしい", id: "aneh, lucu" },
  { jp: "うるさい", id: "berisik" },
  { jp: "やけどをします", id: "luka bakar" },
  { jp: "けがをします", id: "cedera" },
  { jp: "せきがでます", id: "batuk" },
  { jp: "インフルエンザ", id: "influenza" },
  { jp: "そら", id: "langit" },
  { jp: "たいよう", id: "matahari" },
  { jp: "ほし", id: "bintang" },
  { jp: "つき", id: "bulan" },
  { jp: "かぜ", id: "angin" },
  { jp: "きた", id: "utara" },
  { jp: "みなみ", id: "selatan" },
  { jp: "にし", id: "barat" },
  { jp: "ひがし", id: "timur" },
  { jp: "すいどう", id: "air ledeng" },
  { jp: "エンジン", id: "mesin, motor" },
  { jp: "チーム", id: "tim" },
  { jp: "こんや", id: "malam ini" },
  { jp: "ゆうがた", id: "sore" },
  { jp: "まえ", id: "sebelumnya" },
  { jp: "おそく", id: "larut, terlambat" },
  { jp: "こんな", id: "seperti ini" },
  { jp: "そんな", id: "seperti itu" },
  { jp: "あんな", id: "seperti itu (jauh)" },
  { jp: "もしかしたら", id: "mungkin saja" },
  { jp: "それはいけませんね", id: "kasihan ya" },
  { jp: "げんき", id: "sehat" },
  { jp: "い", id: "lambung" },
  { jp: "はたらきすぎ", id: "terlalu banyak bekerja" },
  { jp: "ストレス", id: "stres" },
  { jp: "むりをします", id: "memaksakan diri" },
  { jp: "ゆっくりします", id: "beristirahat" },
  { jp: "ほしうらない", id: "ramalan zodiak" },
  { jp: "おうしざ", id: "zodiak taurus" },
  { jp: "こまります", id: "mengalami kesulitan" },
  { jp: "たからくじ", id: "lotre" },
  { jp: "あたります", id: "menang lotre" },
  { jp: "けんこう", id: "kesehatan" },
  { jp: "れんあい", id: "percintaan" },
  { jp: "おかねもち", id: "orang kaya" },
  { jp: "てんきよほう", id: "prakiraan cuaca" },
  { jp: "こうすいかくりつ", id: "kemungkinan hujan" },
  { jp: "さいこうきおん", id: "suhu tertinggi" },
  { jp: "さいていきおん", id: "suhu terendah" },
  { jp: "はれのちくもり", id: "cerah lalu berawan" },
  { jp: "くもりところによってあめ", id: "berawan, hujan di beberapa tempat" },
  { jp: "ちほう", id: "wilayah" },
  { jp: "にわかあめ", id: "hujan mendadak" },
  { jp: "たいふう", id: "topan" },
  { jp: "にじ", id: "pelangi" },
  { jp: "しつど", id: "kelembaban" },
  { jp: "むしあつい", id: "panas lembab" },
  { jp: "さわやかな", id: "segar" },
  { jp: "かみなり", id: "petir" }],
  33: [  { jp: "にげます", id: "melarikan diri" },
  { jp: "さわぎます", id: "ribut, berbuat gaduh" },
  { jp: "あきらめます", id: "putus asa, menyerah" },
  { jp: "なげます", id: "melempar" },
  { jp: "まもります", id: "mematuhi, melindungi" },
  { jp: "あげます", id: "menaikkan" },
  { jp: "さげます", id: "menurunkan" },
  { jp: "つたえます", id: "menyampaikan" },
  { jp: "ちゅういします", id: "memperingatkan, memperhatikan" },
  { jp: "はずします", id: "tidak ada (di tempat)" },
  { jp: "だめな", id: "tidak boleh, tidak bisa" },
  { jp: "せき", id: "tempat duduk" },
  { jp: "ファイト", id: "semangat, berjuang" },
  { jp: "マーク", id: "tanda" },
  { jp: "ボール", id: "bola" },
  { jp: "せんたくき", id: "mesin cuci" },
  { jp: "~き", id: "mesin ~" },
  { jp: "きそく", id: "peraturan" },
  { jp: "しようきんし", id: "dilarang pakai" },
  { jp: "たちいりきんし", id: "dilarang masuk" },
  { jp: "いりぐち", id: "pintu masuk" },
  { jp: "でぐち", id: "pintu keluar" },
  { jp: "ひじょうぐち", id: "pintu darurat" },
  { jp: "むりょう", id: "gratis" },
  { jp: "ほんじつきゅうぎょう", id: "hari ini tutup" },
  { jp: "えいぎょうちゅう", id: "sedang buka" },
  { jp: "しようちゅう", id: "sedang digunakan" },
  { jp: "~ちゅう", id: "sedang ~" },
  { jp: "どういう", id: "bagaimana, seperti apa" },
  { jp: "もう", id: "tidak lagi (negatif)" },
  { jp: "あと", id: "tinggal ~ lagi" },
  { jp: "ちゅうしゃいはん", id: "pelanggaran parkir" },
  { jp: "そりゃあ", id: "hal itu" },
  { jp: "~いない", id: "dalam ~ (batas)" },
  { jp: "けいさつ", id: "polisi" },
  { jp: "ばっきん", id: "denda" },
  { jp: "でんぽう", id: "telegram" },
  { jp: "ひとびと", id: "orang-orang" },
  { jp: "きゅうよう", id: "urusan mendadak" },
  { jp: "うちます", id: "mengirim (telegram)" },
  { jp: "でんぽうだい", id: "biaya telegram" },
  { jp: "できるだけ", id: "sebisa mungkin" },
  { jp: "みじかく", id: "secara singkat" },
  { jp: "また", id: "dan" },
  { jp: "たとえば", id: "misalnya" },
  { jp: "キトク", id: "kritis, koma" },
  { jp: "おもいびょうき", id: "sakit parah" },
  { jp: "あす", id: "besok" },
  { jp: "るす", id: "tidak ada di rumah" },
  { jp: "るすばん", id: "menjaga rumah" },
  { jp: "おいわい", id: "perayaan" },
  { jp: "なくなります", id: "meninggal" },
  { jp: "かなしみ", id: "kesedihan" },
  { jp: "りようします", id: "menggunakan" },
  { jp: "ひょうしき", id: "tanda, rambu" },
  { jp: "じゅんびちゅう", id: "dalam persiapan" },
  { jp: "へいてん", id: "tutup" },
  { jp: "ていきゅうび", id: "hari libur tetap" },
  { jp: "けしょうしつ", id: "toilet" },
  { jp: "きんえんせき", id: "tempat duduk bebas rokok" },
  { jp: "よやくせき", id: "tempat duduk reservasi" },
  { jp: "かきげんきん", id: "dilarang api" },
  { jp: "われものちゅうい", id: "barang mudah pecah" },
  { jp: "うんてんしょしんしゃちゅうい", id: "pengemudi pemula" },
  { jp: "こうじちゅう", id: "sedang diperbaiki" },
  { jp: "えんそけいひょうはくざいふか", id: "jangan gunakan pemutih" },
  { jp: "てあらい", id: "cuci tangan" },
  { jp: "アイロン(ていおん)", id: "setrika suhu rendah" },
  { jp: "ドライクリーニング", id: "dry cleaning" }],
  34: [{ jp: "みがきます", id: "menggosok (gigi)" },
  { jp: "くみたてます", id: "merakit" },
  { jp: "おります", id: "melipat, mematahkan" },
  { jp: "きがつきます", id: "menyadari" },
  { jp: "つけます", id: "membubuhi" },
  { jp: "みつかります", id: "ketemu, ditemukan" },
  { jp: "します", id: "memakai (aksesoris)" },
  { jp: "しつもんします", id: "bertanya" },
  { jp: "ほそい", id: "tipis" },
  { jp: "ふとい", id: "tebal" },
  { jp: "ぼんおどり", id: "tarian festival bon" },
  { jp: "スポーツクラブ", id: "klub olahraga" },
  { jp: "かぐ", id: "perabot rumah tangga" },
  { jp: "キー", id: "tuts, tombol jari" },
  { jp: "シートベルト", id: "sabuk pengaman" },
  { jp: "せつめいしょ", id: "buku petunjuk" },
  { jp: "ず", id: "gambar" },
  { jp: "せん", id: "garis" },
  { jp: "やじるし", id: "tanda panah" },
  { jp: "くろ", id: "hitam" },
  { jp: "しろ", id: "putih" },
  { jp: "あか", id: "merah" },
  { jp: "あお", id: "biru" },
  { jp: "こん", id: "biru tua" },
  { jp: "きいろ", id: "kuning" },
  { jp: "ちゃいろ", id: "coklat" },
  { jp: "しょうゆ", id: "kecap asin jepang" },
  { jp: "ソース", id: "saus" },
  { jp: "~か~", id: "atau" },
  { jp: "ゆうべ", id: "tadi malam" },
  { jp: "さっき", id: "tadi" },
  { jp: "さどう", id: "upacara minum teh" },
  { jp: "おちゃをたてます", id: "membuat teh jepang" },

  { jp: "さきに", id: "terlebih dahulu" },
  { jp: "のせます", id: "menaruh" },
  { jp: "これでいいですか", id: "ini sudah benar?" },
  { jp: "にがい", id: "pahit" },
  { jp: "おやこどんぶり", id: "nasi ayam telur" },
  { jp: "ざいりょう", id: "bahan" },
  { jp: "~ぶん", id: "bagian" },
  { jp: "とりにく", id: "daging ayam" },
  { jp: "~グラム", id: "gram" },
  { jp: "~こ", id: "buah kecil" },
  { jp: "たまねぎ", id: "bawang bombai" },
  { jp: "よんぶんのいち", id: "seperempat" },
  { jp: "ちょうみりょう", id: "bumbu masak" },
  { jp: "なべ", id: "panci" },
  { jp: "ひ", id: "api" },
  { jp: "ひにかけます", id: "meletakkan di atas api" },
  { jp: "どんぶり", id: "mangkuk besar" },
  { jp: "にる", id: "merebus" },
  { jp: "やく", id: "memanggang" },
  { jp: "あげる", id: "menggoreng" },
  { jp: "いためる", id: "menumis" },
  { jp: "ゆでる", id: "merebus" },
  { jp: "むす", id: "mengukus" },
  { jp: "たく", id: "menanak nasi" },
  { jp: "むく", id: "mengupas" },
  { jp: "きざむ", id: "mencincang" },
  { jp: "かきまぜる", id: "mengaduk" },
  { jp: "す", id: "cuka" },
  { jp: "みそ", id: "miso" },
  { jp: "あぶら", id: "minyak" },
  { jp: "マヨネーズ", id: "mayones" },
  { jp: "ケチャップ", id: "saus tomat" },
  { jp: "からし", id: "mustard" },
  { jp: "こしょう", id: "merica" },
  { jp: "とうがらし", id: "cabe merah" },
  { jp: "わさび", id: "wasabi" },
  { jp: "しょうが", id: "jahe" },
  { jp: "カレーこ", id: "bubuk kari" },
  { jp: "だいどころようひん", id: "perabot dapur" },
  { jp: "やかん", id: "ceret" },
  { jp: "ふた", id: "tutup" },
  { jp: "おたま", id: "sendok sayur" },
  { jp: "まないた", id: "talenan" },
  { jp: "ほうちょう", id: "pisau dapur" },
  { jp: "ふきん", id: "lap dapur" },
  { jp: "フライパン", id: "wajan" },
  { jp: "でんしオープンレンジ", id: "oven microwave" },
  { jp: "すいはんき", id: "rice cooker" },
  { jp: "しゃもじ", id: "sendok nasi" },
  { jp: "かんきり", id: "pembuka kaleng" },
  { jp: "せんぬき", id: "pembuka botol" },
  { jp: "ざる", id: "saringan" },
  { jp: "ポット", id: "termos" },
  { jp: "ガスだい", id: "kompor gas" },
  { jp: "ながしだい", id: "bak cuci piring" },
  { jp: "かんきせん", id: "kipas ventilasi" }],
  35: [  { jp: "さきます", id: "mekar (bunga)" },
  { jp: "かわります", id: "berubah" },
  { jp: "こまります", id: "mengalami kesulitan" },
  { jp: "つけます", id: "memberi tanda" },
  { jp: "ひろいます", id: "memungut, mengambil" },
  { jp: "かかります", id: "ada (telepon)" },
  { jp: "らくな", id: "mudah, ringan" },
  { jp: "ただしい", id: "benar" },
  { jp: "めずらしい", id: "aneh, langka" },
  { jp: "かた", id: "orang" },
  { jp: "むこう", id: "di sebelah sana" },
  { jp: "しま", id: "pulau" },
  { jp: "むら", id: "kampung, desa" },
  { jp: "みなと", id: "pelabuhan" },
  { jp: "きんじょ", id: "tetangga" },
  { jp: "おくじょう", id: "atap, lantai puncak" },
  { jp: "かいがい", id: "luar negeri" },
  { jp: "やまのぼり", id: "pendakian gunung" },
  { jp: "ハイキング", id: "hiking, piknik" },
  { jp: "きかい", id: "kesempatan" },
  { jp: "きょか", id: "izin" },
  { jp: "まる", id: "lingkaran" },
  { jp: "そうさ", id: "pengoperasian" },
  { jp: "ほうほう", id: "cara, metode" },
  { jp: "せつび", id: "peralatan, fasilitas" },
  { jp: "カーテン", id: "korden" },
  { jp: "ひも", id: "tali" },
  { jp: "ふた", id: "tutup" },
  { jp: "は", id: "daun" },
  { jp: "きょく", id: "lagu, musik" },
  { jp: "たのしみ", id: "kesenangan" },
  { jp: "もっと", id: "lebih" },
  { jp: "はじめに", id: "awal, pertama-tama" },
  { jp: "これでおわります", id: "kita akhiri sampai di sini" },
  { jp: "アフリカ", id: "afrika" },
  { jp: "それなら", id: "kalau begitu" },
  { jp: "やこうバス", id: "bus malam" },
  { jp: "りょこうしゃ", id: "agen perjalanan" },
  { jp: "くわしい", id: "detail, terperinci" },
  { jp: "スキーじょう", id: "tempat bermain ski" },
  { jp: "しゅ", id: "merah terang" },
  { jp: "まじわります", id: "bergaul" },
  { jp: "ことわざ", id: "peribahasa" },
  { jp: "なかよくします", id: "hidup rukun" },
  { jp: "ひつような", id: "perlu" }],

  36: [{ jp: "とどきます", id: "sampai (barang)" },
  { jp: "でます", id: "ikut (pertandingan)" },
  { jp: "うちます", id: "mengetik" },
  { jp: "ちょきんします", id: "menabung" },
  { jp: "ふとります", id: "menjadi gemuk" },
  { jp: "やせます", id: "menjadi kurus" },
  { jp: "すぎます", id: "berlalu, melewati (waktu)" },
  { jp: "なれます", id: "terbiasa" },
  { jp: "かたい", id: "keras" },
  { jp: "やわらかい", id: "lunak" },
  { jp: "でんし", id: "elektronik" },
  { jp: "けいたい", id: "mudah dibawa, portable" },
  { jp: "こうじょう", id: "pabrik" },
  { jp: "けんこう", id: "kesehatan" },
  { jp: "けんどう", id: "kendo" },
  { jp: "まいしゅう", id: "setiap minggu" },
  { jp: "まいつき", id: "setiap bulan" },
  { jp: "まいとし", id: "setiap tahun" },
  { jp: "やっと", id: "akhirnya" },
  { jp: "かなり", id: "lumayan, agak" },
  { jp: "かならず", id: "selalu, pasti" },
  { jp: "ぜったいに", id: "sama sekali (negatif)" },
  { jp: "じょうずに", id: "dengan pandai" },
  { jp: "できるだけ", id: "sebisa mungkin" },
  { jp: "このごろ", id: "akhir-akhir ini" },
  { jp: "~ずつ", id: "sedikit demi sedikit" },
  { jp: "そのほうが", id: "yang itu lebih baik" },
  { jp: "おきゃくさま", id: "tamu, pelanggan" },
  { jp: "とくべつな", id: "istimewa, khusus" },
  { jp: "していらっしゃいます", id: "sedang melakukan (hormat)" },
  { jp: "すいえい", id: "renang" },
  { jp: "~とか~とか", id: "atau ini itu dan lain-lain" },
  { jp: "タンゴ", id: "tango" },
  { jp: "チャレンジします", id: "menantang, mencoba" },
  { jp: "きもち", id: "perasaan, keinginan" },
  { jp: "のりもの", id: "kendaraan" },
  { jp: "れきし", id: "sejarah" },
  { jp: "~せいき", id: "abad" },
  { jp: "とおく", id: "jauh" },
  { jp: "きしゃ", id: "kereta api" },
  { jp: "きせん", id: "kapal api" },
  { jp: "おおぜいの", id: "banyak (orang)" },
  { jp: "はこびます", id: "membawa, mengangkut" },
  { jp: "とびます", id: "terbang" },
  { jp: "あんぜんな", id: "aman" },
  { jp: "うちゅう", id: "luar angkasa" },
  { jp: "ちきゅう", id: "bumi" },
  { jp: "きそくただしいせいかつをする", id: "hidup teratur" },
  { jp: "はやね、はやおきをする", id: "tidur cepat dan bangun pagi" },
  { jp: "うんどうする", id: "berolahraga" },
  { jp: "よくあるく", id: "banyak berjalan kaki" },
  { jp: "すききらいがない", id: "tidak pilih-pilih makanan" },
  { jp: "えいようのバランスをかんがえてたべる", id: "makan dengan gizi seimbang" },
  { jp: "けんこうしだんをうける", id: "memeriksa kesehatan" },
  { jp: "よふかしをする", id: "sering begadang" },
  { jp: "あまりうんどうしない", id: "kurang berolahraga" },
  { jp: "すききらいがある", id: "pilih-pilih makanan" },
  { jp: "よくインスタントしょくひんをたべる", id: "sering makan makanan instan" },
  { jp: "がいしょくがおおい", id: "sering makan di luar" },
  { jp: "たばこをすう", id: "banyak merokok" },
  { jp: "よくおさけをのむ", id: "sering minum alkohol" },
  { jp: "えいようそ", id: "nutrisi" },
  { jp: "ふくむ", id: "mengandung" },
  { jp: "たんすいかぶつ", id: "karbohidrat" },
  { jp: "いも", id: "umbi-umbian" },
  { jp: "しぼう", id: "lemak" },
  { jp: "とうふ", id: "tahu" },
  { jp: "たんぱくしつ", id: "protein" },
  { jp: "まめ", id: "kacang-kacangan" },
  { jp: "のり", id: "rumput laut kering" },
  { jp: "カルシウム", id: "kalsium" },
  { jp: "かいそう", id: "rumput laut basah" },
  { jp: "ビタミン", id: "vitamin" }],
  37: [{ jp: "ほめます", id: "memuji" },
  { jp: "しかります", id: "memarahi" },
  { jp: "さそいます", id: "mengajak" },
  { jp: "おこします", id: "membangunkan (orang)" },
  { jp: "しょうたいします", id: "mengundang" },
  { jp: "たのみます", id: "meminta" },
  { jp: "ちゅういします", id: "memberi peringatan" },
  { jp: "とります", id: "mencuri" },
  { jp: "ふみます", id: "menginjak" },
  { jp: "こわします", id: "merusakkan, memecahkan" },
  { jp: "よごします", id: "mengotori" },
  { jp: "おこないます", id: "mengadakan, melangsungkan" },
  { jp: "ゆしゅつします", id: "mengekspor" },
  { jp: "ゆにゅうします", id: "mengimpor" },
  { jp: "ほんやくします", id: "menerjemahkan" },
  { jp: "はつめいします", id: "menciptakan" },
  { jp: "はっけんします", id: "menemukan" },
  { jp: "せっけいします", id: "merancang, mendesain" },
  { jp: "こめ", id: "beras" },
  { jp: "むぎ", id: "gandum" },
  { jp: "せきゆ", id: "minyak bumi" },
  { jp: "げんりょう", id: "bahan mentah" },
  { jp: "デート", id: "kencan, pacaran" },
  { jp: "どろぼう", id: "pencuri" },
  { jp: "けいかん", id: "polisi" },
  { jp: "けんちくか", id: "arsitek" },
  { jp: "かがくしゃ", id: "ilmuwan" },
  { jp: "まんが", id: "komik, kartun" },
  { jp: "せかいじゅう", id: "seluruh dunia" },
  { jp: "~じゅう", id: "seluruh" },
  { jp: "~によって", id: "oleh, tergantung" },
  { jp: "うめたてます", id: "menimbun" },
  { jp: "ぎじゅつ", id: "teknik, teknologi" },
  { jp: "とち", id: "tanah" },
  { jp: "そうおん", id: "suara bising" },
  { jp: "りようします", id: "memakai, memanfaatkan" },
  { jp: "アクセス", id: "akses, jalan masuk" },
  { jp: "~せいき", id: "abad" },
  { jp: "ごうかな", id: "mewah, megah" },
  { jp: "ちょうこく", id: "seni pahat" },
  { jp: "ねむります", id: "tidur" },
  { jp: "ほります", id: "memahat" },
  { jp: "なかま", id: "teman, kawan" },
  { jp: "そのあと", id: "sesudah itu" },
  { jp: "いっしょうけんめい", id: "dengan sekuat tenaga" },
  { jp: "ねずみ", id: "tikus" },
  { jp: "いっぴきもいません", id: "seekor pun tidak ada" },
  { jp: "ねむりねこ", id: "kucing tidur" },
  { jp: "ころす", id: "membunuh" },
  { jp: "うつ", id: "menembak" },
  { jp: "さす", id: "menusuk" },
  { jp: "かむ", id: "menggigit" },
  { jp: "ひく", id: "menggilas" },
  { jp: "はねる", id: "menabrak" },
  { jp: "しょうとつする", id: "tabrakan" },
  { jp: "ついとつする", id: "menabrak dari belakang" },
  { jp: "ぬすむ", id: "mencuri" },
  { jp: "ゆうかいする", id: "menculik" },
  { jp: "ハイジャックする", id: "membajak" },
  { jp: "ついらくする", id: "jatuh (kecelakaan)" },
  { jp: "はこぶ", id: "membawa" },
  { jp: "たすける", id: "menolong" },
  { jp: "ばくはつする", id: "meledak" },
  { jp: "ちんぼつする", id: "tenggelam" }],
  38: [ { jp: "そだてます", id: "memelihara, membesarkan" },
  { jp: "はこびます", id: "membawa, mengangkut" },
  { jp: "なくなります", id: "meninggal (hormat)" },
  { jp: "にゅういんします", id: "masuk rumah sakit" },
  { jp: "たいいんします", id: "keluar dari rumah sakit" },
  { jp: "いれます", id: "menghidupkan (listrik)" },
  { jp: "きります", id: "mematikan (listrik)" },
  { jp: "かけます", id: "mengunci" },
  { jp: "きもちがいい", id: "merasa enak, senang" },
  { jp: "きもちがわるい", id: "merasa tidak enak, jijik" },
  { jp: "おおきな", id: "besar" },
  { jp: "ちいさな", id: "kecil" },
  { jp: "あかちゃん", id: "bayi" },
  { jp: "しょうがっこう", id: "SD" },
  { jp: "ちゅうがっこう", id: "SMP" },
  { jp: "えきまえ", id: "depan stasiun" },
  { jp: "かいがん", id: "pantai" },
  { jp: "うそ", id: "bohong" },
  { jp: "しょるい", id: "dokumen, surat" },
  { jp: "でんげん", id: "aliran listrik" },
  { jp: "~せい", id: "buatan" },
  { jp: "あ、いけない", id: "aduh celaka" },
  { jp: "おさきにしつれいします", id: "saya permisi duluan" },
  { jp: "かいらん", id: "edaran" },
  { jp: "けんきゅうしつ", id: "ruang penelitian" },
  { jp: "きちんと", id: "dengan rapi" },
  { jp: "せいりします", id: "merapikan" },
  { jp: "~さつ", id: "satuan buku" },
  { jp: "はんこ", id: "stempel" },
  { jp: "おします", id: "menyetempel" },
  { jp: "ふたご", id: "kembar" },
  { jp: "しまい", id: "saudara perempuan" },
  { jp: "5ねんせい", id: "kelas 5" },
  { jp: "にています", id: "mirip" },
  { jp: "せいかく", id: "sifat, tabiat" },
  { jp: "おとなしい", id: "pendiam, patuh" },
  { jp: "せわをします", id: "mengurus" },
  { jp: "じかんがたちます", id: "waktu berlalu" },
  { jp: "だいすきな", id: "suka sekali" },
  { jp: "~てん", id: "angka, skor" },
  { jp: "クラス", id: "kelas" },
  { jp: "けんかします", id: "bertengkar" },
  { jp: "ふしぎな", id: "aneh, luar biasa" },
  { jp: "ねんちゅうぎょうじ", id: "acara tahunan jepang" },
  { jp: "おしょうがつ", id: "tahun baru" },
  { jp: "ひなまつり", id: "festival anak perempuan" },
  { jp: "たなばた", id: "festival bintang" },
  { jp: "おぼん", id: "festival bon" },
  { jp: "おつきみ", id: "melihat bulan" },
  { jp: "おおみそか", id: "hari terakhir tahun" }],
  39: [  { jp: "こたえます", id: "menjawab" },
  { jp: "たおれます", id: "roboh, tumbang" },
  { jp: "やけます", id: "terbakar, dipanggang" },
  { jp: "とおります", id: "melewati" },
  { jp: "しにます", id: "meninggal" },
  { jp: "びっくりします", id: "terkejut" },
  { jp: "がっかりします", id: "kecewa" },
  { jp: "あんしんします", id: "lega" },
  { jp: "ちこくします", id: "terlambat" },
  { jp: "そうたいします", id: "pulang lebih awal" },
  { jp: "りこんします", id: "bercerai" },
  { jp: "けんかします", id: "bertengkar" },
  { jp: "ふくざつな", id: "rumit" },
  { jp: "じゃまな", id: "mengganggu" },
  { jp: "きたない", id: "kotor" },
  { jp: "うれしい", id: "senang" },
  { jp: "かなしい", id: "sedih" },
  { jp: "はずかしい", id: "malu" },
  { jp: "じしん", id: "gempa bumi" },
  { jp: "たいふう", id: "topan" },
  { jp: "かじ", id: "kebakaran" },
  { jp: "じこ", id: "kecelakaan" },
  { jp: "おみあい", id: "perjodohan" },
  { jp: "でんわだい", id: "biaya telepon" },
  { jp: "~だい", id: "biaya, ongkos" },
  { jp: "フロント", id: "resepsionis hotel" },
  { jp: "~ごうしつ", id: "nomor kamar" },
  { jp: "あせ", id: "keringat" },
  { jp: "タオル", id: "handuk" },
  { jp: "せっけん", id: "sabun" },
  { jp: "おおぜい", id: "banyak orang" },
  { jp: "おつかれさまでした", id: "terima kasih atas kerja kerasnya" },
  { jp: "うかがいます", id: "datang (hormat)" },
  { jp: "とちゅう", id: "di tengah perjalanan" },
  { jp: "トラック", id: "truk" },
  { jp: "ぶつかります", id: "bertabrakan" },
  { jp: "ならびます", id: "antre" },
  { jp: "おとな", id: "orang dewasa" },
  { jp: "ようふく", id: "pakaian barat" },
  { jp: "せいようかします", id: "westernisasi" },
  { jp: "あいます", id: "cocok" },
  { jp: "いまでは", id: "sekarang" },
  { jp: "せいじんしき", id: "upacara kedewasaan" },
  { jp: "きもち", id: "perasaan" },
  { jp: "たのしい", id: "menyenangkan" },
  { jp: "さびしい", id: "kesepian" },
  { jp: "うらやましい", id: "iri" },
  { jp: "なつかしい", id: "kangen" },
  { jp: "うっとりする", id: "terpesona" },
  { jp: "いらいらする", id: "kesal" },
  { jp: "どきどきする", id: "berdebar" },
  { jp: "はらはらする", id: "cemas" },
  { jp: "わくわくする", id: "tidak sabar" }],
  40: [ { jp: "かぞえます", id: "menghitung" },
  { jp: "はかります", id: "mengukur, menimbang" },
  { jp: "たしかめます", id: "memastikan" },
  { jp: "あいます", id: "tepat, cocok" },
  { jp: "しゅっぱつします", id: "berangkat" },
  { jp: "とうちゃくします", id: "tiba" },
  { jp: "よいます", id: "mabuk" },
  { jp: "きけんな", id: "berbahaya" },
  { jp: "ひつような", id: "perlu" },
  { jp: "うちゅう", id: "luar angkasa" },
  { jp: "ちきゅう", id: "bumi" },
  { jp: "ぼうねんかい", id: "pesta akhir tahun" },
  { jp: "しんねんかい", id: "pesta tahun baru" },
  { jp: "にじかい", id: "acara lanjutan" },
  { jp: "たいかい", id: "perlombaan" },
  { jp: "マラソン", id: "maraton" },
  { jp: "コンテスト", id: "kontes" },
  { jp: "おもて", id: "bagian depan" },
  { jp: "うら", id: "bagian belakang" },
  { jp: "へんじ", id: "jawaban" },
  { jp: "もうしこみ", id: "pendaftaran" },
  { jp: "ほんとう", id: "kebenaran" },
  { jp: "まちがい", id: "kesalahan" },
  { jp: "きず", id: "luka" },
  { jp: "ズボン", id: "celana panjang" },
  { jp: "ながさ", id: "panjang" },
  { jp: "おもさ", id: "berat" },
  { jp: "たかさ", id: "tinggi" },
  { jp: "おおきさ", id: "besar" },
  { jp: "~びん", id: "nomor penerbangan" },
  { jp: "~ごう", id: "nomor" },
  { jp: "~こ", id: "satuan benda kecil" },
  { jp: "~ほん", id: "satuan benda panjang" },
  { jp: "~はい", id: "satuan gelas" },
  { jp: "~キロ", id: "kilogram, kilometer" },
  { jp: "~グラム", id: "gram" },
  { jp: "~センチ", id: "sentimeter" },
  { jp: "~ミリ", id: "milimeter" },
  { jp: "~いじょう", id: "lebih dari" },
  { jp: "~いか", id: "kurang dari" },
  { jp: "さあ", id: "bagaimana ya" },
  { jp: "どうでしょうか", id: "bagaimana?" },
  { jp: "テスト", id: "ujian" },
  { jp: "せいせき", id: "nilai, prestasi" },
  { jp: "ところで", id: "ngomong-ngomong" },
  { jp: "いらっしゃいます", id: "datang (sopan)" },
  { jp: "ようす", id: "keadaan" },
  { jp: "じけん", id: "peristiwa" },
  { jp: "オートバイ", id: "sepeda motor" },
  { jp: "ばくだん", id: "bom" },
  { jp: "つみます", id: "memuat" },
  { jp: "うんてんしゅ", id: "supir" },
  { jp: "はなれた", id: "terpencil" },
  { jp: "きゅうに", id: "tiba-tiba" }],

  41: [ { jp: "いただきます", id: "menerima (bentuk merendah)" },
  { jp: "くださいます", id: "memberi (bentuk hormat)" },
  { jp: "やります", id: "memberikan (ke bawahan, hewan, tanaman)" },
  { jp: "よびます", id: "memanggil" },
  { jp: "とりかえます", id: "mengganti, menukar" },
  { jp: "しんせつにします", id: "bersikap ramah" },
  { jp: "かわいい", id: "imut, cantik" },
  { jp: "おいわいします", id: "merayakan, memberi hadiah" },
  { jp: "おとしだま", id: "uang hadiah tahun baru" },
  { jp: "おみまい", id: "menjenguk orang sakit" },
  { jp: "きょうみ", id: "minat" },
  { jp: "じょうほう", id: "informasi" },
  { jp: "ぶんぽう", id: "tata bahasa" },
  { jp: "はつおん", id: "pelafalan" },
  { jp: "さる", id: "monyet" },
  { jp: "えさ", id: "makanan hewan" },
  { jp: "おもちゃ", id: "mainan" },
  { jp: "えほん", id: "buku bergambar" },
  { jp: "えはがき", id: "kartu pos bergambar" },
  { jp: "ドライバー", id: "obeng" },
  { jp: "ハンカチ", id: "saputangan" },
  { jp: "くつした", id: "kaos kaki" },
  { jp: "てぶくろ", id: "sarung tangan" },
  { jp: "ゆびわ", id: "cincin" },
  { jp: "バッグ", id: "tas" },
  { jp: "そふ", id: "kakek (sendiri)" },
  { jp: "そぼ", id: "nenek (sendiri)" },
  { jp: "まご", id: "cucu" },
  { jp: "おじ", id: "paman (sendiri)" },
  { jp: "おじさん", id: "paman (orang lain)" },
  { jp: "おば", id: "bibi (sendiri)" },
  { jp: "おばさん", id: "bibi (orang lain)" },
  { jp: "おととし", id: "dua tahun lalu" },
  { jp: "もうしわけありません", id: "maaf" },
  { jp: "あずかります", id: "menitipkan, menjaga" },
  { jp: "せんじつ", id: "beberapa hari lalu" },
  { jp: "たすかります", id: "tertolong" },
  { jp: "むかしばなし", id: "cerita rakyat" },
  { jp: "ある", id: "suatu" },
  { jp: "いじめます", id: "menyiksa, mengganggu" },
  { jp: "かめ", id: "kura-kura" },
  { jp: "たすけます", id: "menolong" },
  { jp: "おしろ", id: "kastil" },
  { jp: "おひめさま", id: "putri" },
  { jp: "たのしく", id: "dengan gembira" },
  { jp: "くらします", id: "hidup" },
  { jp: "りく", id: "daratan" },
  { jp: "すると", id: "lalu, kemudian" },
  { jp: "けむり", id: "asap" },
  { jp: "まっしろな", id: "putih sekali" },
  { jp: "なかみ", id: "isi" }],
  42: [ { jp: "つつみます", id: "membungkus" },
  { jp: "わかします", id: "merebus" },
  { jp: "まぜます", id: "mencampur" },
  { jp: "けいさんします", id: "menghitung" },
  { jp: "あつい", id: "tebal" },
  { jp: "うすい", id: "tipis" },
  { jp: "べんごし", id: "pengacara" },
  { jp: "おんがくか", id: "musisi" },
  { jp: "きょういく", id: "pendidikan" },
  { jp: "れきし", id: "sejarah" },
  { jp: "ぶんか", id: "budaya" },
  { jp: "しゃかい", id: "masyarakat" },
  { jp: "ほうりつ", id: "hukum" },
  { jp: "せんそう", id: "perang" },
  { jp: "へいわ", id: "damai" },
  { jp: "もくてき", id: "tujuan" },
  { jp: "あんぜん", id: "keamanan" },
  { jp: "ろんぶん", id: "skripsi, tesis" },
  { jp: "かんけい", id: "hubungan" },
  { jp: "ミキサー", id: "blender" },
  { jp: "やかん", id: "teko" },
  { jp: "せんぬき", id: "pembuka botol" },
  { jp: "かんきり", id: "pembuka kaleng" },
  { jp: "かんづめ", id: "makanan kaleng" },
  { jp: "ふろしき", id: "kain pembungkus" },
  { jp: "そろばん", id: "sempoa" },
  { jp: "たいおんけい", id: "termometer" },
  { jp: "ざいりょう", id: "bahan" },
  { jp: "いし", id: "batu" },
  { jp: "ピラミッド", id: "piramida" },
  { jp: "データ", id: "data" },
  { jp: "ファイル", id: "file" },
  { jp: "なぜ", id: "mengapa" },
  { jp: "こくれん", id: "PBB" },
  { jp: "ローン", id: "kredit" },
  { jp: "セット", id: "set" },
  { jp: "あと", id: "sisa" }],
  43: [ { jp: "ふえます", id: "bertambah" },
  { jp: "へります", id: "berkurang" },
  { jp: "あがります", id: "naik" },
  { jp: "さがります", id: "turun" },
  { jp: "きれます", id: "putus" },
  { jp: "とれます", id: "lepas" },
  { jp: "おちます", id: "jatuh" },
  { jp: "なくなります", id: "habis" },
  { jp: "じょうぶな", id: "kuat" },
  { jp: "へんな", id: "aneh" },
  { jp: "しあわせな", id: "bahagia" },
  { jp: "うまい", id: "enak, mahir" },
  { jp: "まずい", id: "tidak enak" },
  { jp: "つまらない", id: "membosankan" },
  { jp: "ガソリン", id: "bensin" },
  { jp: "だんぼう", id: "pemanas" },
  { jp: "れいぼう", id: "AC" },
  { jp: "センス", id: "selera" },
  { jp: "かいいん", id: "anggota" },
  { jp: "ねんれい", id: "usia" },
  { jp: "しゅうにゅう", id: "penghasilan" },
  { jp: "ぴったり", id: "pas" }],
  44: [ { jp: "なきます", id: "menangis" },
  { jp: "わらいます", id: "tertawa" },
  { jp: "かわきます", id: "mengering" },
  { jp: "ぬれます", id: "basah" },
  { jp: "すべります", id: "terpeleset" },
  { jp: "おきます", id: "terjadi" },
  { jp: "ちょうせつします", id: "mengatur" },
  { jp: "あんぜんな", id: "aman" },
  { jp: "ていねいな", id: "sopan, rapi" },
  { jp: "こまかい", id: "detail, kecil" },
  { jp: "なみだ", id: "air mata" },
  { jp: "わしょく", id: "makanan jepang" },
  { jp: "ようしょく", id: "makanan barat" },
  { jp: "りゆう", id: "alasan" },
  { jp: "びよういん", id: "salon" },
  { jp: "りはつてん", id: "tukang cukur" },
  { jp: "パーマ", id: "rambut keriting" },
  { jp: "ポニーテール", id: "kuncir" }],
  45: [  { jp: "あやまります", id: "meminta maaf" },
  { jp: "しんじます", id: "percaya" },
  { jp: "よういします", id: "mempersiapkan" },
  { jp: "キャンセルします", id: "membatalkan" },
  { jp: "うまくいきます", id: "berjalan lancar" },
  { jp: "ほしょうしょ", id: "garansi" },
  { jp: "りょうしゅうしょ", id: "kwitansi" },
  { jp: "おくりものをします", id: "memberi hadiah" },
  { jp: "キャンプ", id: "berkemah" },
  { jp: "ちゅうし", id: "pembatalan" },
  { jp: "ゆうしょうします", id: "menjadi juara" },
  { jp: "なやみ", id: "masalah, kesusahan" },
  { jp: "めざましとけい", id: "jam alarm" },
  { jp: "ねむります", id: "tidur" },
  { jp: "めがさめます", id: "terbangun" },
  { jp: "きんきゅう", id: "darurat" }],

  46: [{ jp: "やきます", id: "membakar" },
  { jp: "わたします", id: "menyerahkan" },
  { jp: "かえってきます", id: "kembali lagi" },
  { jp: "でます", id: "berangkat (bis)" },
  { jp: "るす", id: "tidak ada di rumah" },
  { jp: "たくはいびん", id: "jasa pengantaran barang" },
  { jp: "げんいん", id: "penyebab" },
  { jp: "ちゅうしゃ", id: "suntikan" },
  { jp: "しょくよく", id: "nafsu makan" },
  { jp: "パンフレット", id: "brosur" },
  { jp: "ステレオ", id: "stereo" },
  { jp: "こちら", id: "sebelah sini" },
  { jp: "ちょうど", id: "pas, tepat" },
  { jp: "たったいま", id: "baru saja" },
  { jp: "いまいいでしょうか", id: "bolehkah bicara sekarang?" },
  { jp: "ガスサービスセンター", id: "pusat layanan gas" },
  { jp: "ガスレンジ", id: "kompor gas" },
  { jp: "ぐあい", id: "keadaan" },
  { jp: "どちらさまでしょうか", id: "anda siapa?" },
  { jp: "むかいます", id: "menuju ke" },
  { jp: "おまたせしました", id: "maaf telah menunggu" },
  { jp: "ちしき", id: "pengetahuan" },
  { jp: "システム", id: "sistem" },
  { jp: "キーワード", id: "kata kunci" },
  { jp: "にゅうりょくします", id: "memasukkan (input)" },
  { jp: "びょう", id: "detik" },
  { jp: "ストレス", id: "stres" },
  { jp: "ドラマ", id: "drama" },
  { jp: "スケジュール", id: "jadwal" },
  { jp: "トラブル", id: "masalah" },
  { jp: "レジャー", id: "waktu santai" },
  { jp: "アルバイト", id: "kerja paruh waktu" },
  { jp: "エネルギー", id: "energi" },
  { jp: "テーマ", id: "tema" },
  { jp: "ビール", id: "bir" },
  { jp: "コーヒー", id: "kopi" }],
  47: [ { jp: "あつまります", id: "berkumpul" },
  { jp: "わかれます", id: "berpisah" },
  { jp: "ながいきします", id: "berumur panjang" },
  { jp: "おとがします", id: "terdengar suara" },
  { jp: "こえがします", id: "terdengar suara" },
  { jp: "あじがします", id: "terasa" },
  { jp: "においがします", id: "tercium bau" },
  { jp: "さします", id: "membuka (payung)" },
  { jp: "ひどい", id: "parah, luar biasa" },
  { jp: "こわい", id: "takut" },
  { jp: "てんきよほう", id: "prakiraan cuaca" },
  { jp: "はっぴょう", id: "pengumuman, presentasi" },
  { jp: "じっけん", id: "percobaan" },
  { jp: "じんこう", id: "jumlah penduduk" },
  { jp: "さんせい", id: "setuju" },
  { jp: "はんたい", id: "tidak setuju" },
  { jp: "だんせい", id: "pria" },
  { jp: "じょせい", id: "wanita" },
  { jp: "こんやくします", id: "bertunangan" },
  { jp: "あいて", id: "pasangan" },
  { jp: "くらべます", id: "membandingkan" },
  { jp: "はかせ", id: "doktor" },
  { jp: "のう", id: "otak" },
  { jp: "けしょうします", id: "berdandan" }],
  48: [ { jp: "おろします", id: "menurunkan" },
  { jp: "とどけます", id: "mengantarkan" },
  { jp: "せわをします", id: "mengurus" },
  { jp: "いやな", id: "tidak suka" },
  { jp: "きびしい", id: "keras, disiplin" },
  { jp: "じゅく", id: "bimbel" },
  { jp: "せいと", id: "murid" },
  { jp: "にゅうかん", id: "kantor imigrasi" },
  { jp: "じゆうに", id: "dengan bebas" },
  { jp: "ひさしぶり", id: "lama tidak bertemu" },
  { jp: "えいぎょう", id: "bisnis" },
  { jp: "かまいません", id: "tidak apa-apa" },
  { jp: "たのしみます", id: "menikmati" },
  { jp: "もともと", id: "pada dasarnya" },
  { jp: "きょうそうします", id: "berlomba" },
  { jp: "うつくしい", id: "indah" },
  { jp: "こころ", id: "hati" },
  { jp: "けいけんをする", id: "berpengalaman" },
  { jp: "ボランティア", id: "relawan" },
  { jp: "さんかします", id: "berpartisipasi" },
  { jp: "がまんします", id: "bersabar" }],
  49: [  { jp: "つとめます", id: "bekerja (di perusahaan)" },
  { jp: "やすみます", id: "beristirahat" },
  { jp: "すごします", id: "menghabiskan waktu" },
  { jp: "よります", id: "mampir" },
  { jp: "いらっしゃいます", id: "datang/pergi (hormat)" },
  { jp: "めしあがります", id: "makan/minum (hormat)" },
  { jp: "おっしゃいます", id: "mengatakan (hormat)" },
  { jp: "なさいます", id: "melakukan (hormat)" },
  { jp: "ごらんになります", id: "melihat (hormat)" },
  { jp: "ごぞんじです", id: "mengetahui (hormat)" },
  { jp: "あいさつ", id: "salam" },
  { jp: "りょかん", id: "penginapan jepang" },
  { jp: "かいじょう", id: "tempat acara" },
  { jp: "たまに", id: "sesekali" },
  { jp: "えんりょなく", id: "tanpa sungkan" },
  { jp: "しつれいいたします", id: "permisi (merendah)" },
  { jp: "じゅしょうします", id: "menerima penghargaan" },
  { jp: "さくひん", id: "karya" },
  { jp: "さっか", id: "pengarang" }],
  50: [ { jp: "まいります", id: "pergi/dat ang (merendah)" },
  { jp: "おります", id: "ada (merendah)" },
  { jp: "いただきます", id: "makan/minum/menerima (merendah)" },
  { jp: "もうします", id: "mengatakan (merendah)" },
  { jp: "いたします", id: "melakukan (merendah)" },
  { jp: "はいけんします", id: "melihat (merendah)" },
  { jp: "うかがいます", id: "bertanya/mengunjungi (merendah)" },
  { jp: "おめにかかります", id: "bertemu (merendah)" },
  { jp: "ございます", id: "ada (sopan)" },
  { jp: "わたくし", id: "saya (merendah)" },
  { jp: "さらいしゅう", id: "dua minggu lagi" },
  { jp: "さらいげつ", id: "dua bulan lagi" },
  { jp: "さらいねん", id: "dua tahun lagi" },
  { jp: "ただいま", id: "sekarang (sopan)" },
  { jp: "きんちょうします", id: "gugup" },
  { jp: "きょうりょくします", id: "bekerja sama" },
  { jp: "かんしゃします", id: "berterima kasih" },
  { jp: "はいけい", id: "dengan hormat" },
  { jp: "けいぐ", id: "hormat saya" }]
};
